### ISSUE TITLE
BarElement ConcentratedLoad returns incorrect results for moments

### ISSUE THREAD

**Issue by SerGlushko** [BriefFiniteElementNet/BriefFiniteElement.Net#101]
**Describe the bug**
Greetings! I've tried to apply moment as a ConcentratedLoad to a BarElement and I was getting varying incorrect support reactions depending on the IsoPoint. When the moment is applied to IsoPoint -1.0 or 1.0, however, the results are correct.

**To Reproduce**
This is the code We've used and caused wrong result/ runtime error

```
var m1 = new Model();
m1.Nodes.Add(new Node(0, 0, 0) { Label = "n1" });
m1.Nodes.Add(new Node(0, 0, 6) { Label = "n2" });
m1.Nodes["n1"].Constraints = new Constraint(dx: DofConstraint.Fixed, dy: DofConstraint.Fixed, dz: DofConstraint.Fixed, rx: DofConstraint.Fixed, ry: DofConstraint.Fixed, rz: DofConstraint.Fixed);
m1.Elements.Add(new BarElement(m1.Nodes["n1"], m1.Nodes["n2"]) { Label = "r1" });
(m1.Elements["r1"] as BarElement).Behavior = BarElementBehaviours.FullFrame;
(m1.Elements["r1"] as BarElement).Section = new BriefFiniteElementNet.Sections.UniformParametric1DSection(16.43 / 10000, 541.22 / 100000000, 44.92 / 100000000, 541.22 / 100000000 + 44.92 / 100000000);
(m1.Elements["r1"] as BarElement).Material = BriefFiniteElementNet.Materials.UniformIsotropicMaterial.CreateFromYoungPoisson(210 * Math.Pow(10, 9), 0.3);
m1.Elements["r1"].Loads.Add(new BriefFiniteElementNet.Loads.ConcentratedLoad(new Force(0, 0, 0, 0, -2000, 0), new IsoPoint(0.0), CoordinationSystem.Global)); //The moment is applied to the center point of the element
m1.Solve();
var r11 = m1.Nodes[0].GetSupportReaction();
var r12 = m1.Nodes[1].GetSupportReaction();
Console.WriteLine("n0 reaction: {0}", r11);
Console.WriteLine("n1 reaction: {0}", r12);
Console.ReadKey();
```

**Expected behavior**
Although near-zero Fx result for n1 is exected, My must be equal to -2000

**Additional context**
The illustration:

![image](https://user-images.githubusercontent.com/22731503/101034209-72579200-358b-11eb-9e64-dc7870e26568.png)

Current results are as follows:

![image](https://user-images.githubusercontent.com/22731503/101030082-47207300-358a-11eb-8d40-21bd7c1347f6.png)

**Comment by epsi1on** [comment]
If user applies moment about `Z` instead of `Y`, then result is right.

probably there is problem with
`EulerBernoulliBeamHelper.GetLocalEquivalentNodalLoads()`
or
`EulerBernoulliBeamHelper.GetLocalInternalForceAt()`

**Comment by SerGlushko** [comment]
I've got a question about legacy components.
Since FrameElement2Node is now legacy, are there any plans and maybe a time frame on ConcentratedLoad support for this type of element too? Thanks in advance.

**Comment by epsi1on** [comment]
This issue is in progress. 
Currently no plan to develop legacy code.
Thanks

**Comment by epsi1on** [comment]
Problem fixed, it should work fine now,

Could you please also test the correctness of internal force of this beam? (I mean `GetExactInternalForce()` method)?

![image](https://user-images.githubusercontent.com/7839141/104603705-eb213200-5691-11eb-92b0-1ed8dc0a0bdc.png)

Thanks

**Comment by SerGlushko** [comment]
It seems the results are correct for both support reactions and internal forces in this example.

![image](https://user-images.githubusercontent.com/22731503/104892582-6846f280-5983-11eb-8fda-cc2294292502.png)

Trying to read exactly at the point where the moment is applied throws an exception, but I guess there's no way around it.
Thanks!

**Comment by epsi1on** [comment]
> Trying to read exactly at the point where the moment is applied throws an exception, but I guess there's no way around it.

Yes because the moment is not a single value at the point that moment is applied. Take a look at this example image:

![image](https://user-images.githubusercontent.com/7839141/104927379-9abe1300-59b6-11eb-9e90-2726dcc2ebc0.png)

you can calculate exact internal force a little before (like 1e-9) and a little after this location and draw or do the rest of calculation.

Take a look at file `BarElement.cs` method 

`public Force GetExactInternalForceAt(double xi, LoadCase loadCase)`

to see how these points are calculated.
