### ISSUE TITLE
Anybody interested in writing a quad mesher for a 2D surface ?

### ISSUE THREAD

**Issue by upuri** [BriefFiniteElementNet/BriefFiniteElement.Net#106]
An automatic 2D quadrilateral mesher for a closed polygon with holes, points and lines constraint in it. Programming language C#

**Comment by epsi1on** [comment]
There should be some solution and codes to use Deluanay triangulation to form a quad mesh for polygon, i can remember another user just asked same question, I think you could find it in issues section by some search

**Comment by upuri** [comment]
done
