### ISSUE TITLE
The Results of the Reactions in nodes of supported Wall elements are reported as zero.

### ISSUE THREAD

**Issue by MLiranzo** [BriefFiniteElementNet/BriefFiniteElement.Net#135]
Hello Mr. eps1on,
Finally I was able to integrate a wall element in a frame structure formed by beams and columns using BriefFiniteElementNet, now I have a situation and that is that no reaction results are reported in the wall elements, that is, all the reaction components are zero. I have added fixed constraints on the support nodes, the triangular elements of walls and the nodes are inserted correctly.

**Comment by MLiranzo** [comment]
Hi eps1on,
I am not using MPC elements, the deformations are generated although I have not verified their validity, the loads are not applied directly to the nodes of the walls; I am assuming that, since it is an integrated model with frame elements and walls, the loads applied to other nodes also act on the wall elements. I am using custom LoadCase, I am not getting results from DefaultLoadCase. I receive results from the nodes of the frame elements (beams and columns).
![modelo](https://user-images.githubusercontent.com/53960987/167743186-3f634419-5c71-4ba3-b1c5-2715f84d9cc4.png)

**Comment by epsi1on** [comment]
sorry, my mistake. do you mean only support forces are zero, and other things like internal forces are non-zero?

**Comment by MLiranzo** [comment]
Hi eps1on,
I have not been able to obtain any type of response, I have tried the reactions and the results are zero, however, the internal forces in the plates are not, because when I instantiate " **var cauchy = el.GetInternalStress(new double[] { dx, dy, dz }, lstE[k], SectionPoints.Envelope);** " an "Object reference not set to an instance of an object" exception is generated which tells me that I might not be receiving any response.

**Comment by epsi1on** [comment]
first you need to make sure you have nonzero displacements, i.e. displacements inside `Model.LastResult.Displacements` are nonzero. displacements are stored in a dictionary with `LoadCase` as key and a `double[]` as value. you need to check the value. Or you can simply save your model into a file (using `Model.Save()`) and send it here.
Also note that QuadrilaturalElement is not tested yet, you better use `TriangleElement` for your purpose.

**Comment by MLiranzo** [comment]
Hi eps1on,
I have verified that the displacements of the nodes other than the wall supports are different from zero. I am using TriangleElements. I have not been able to implement "Model.Save();" because the following Exception is generated: "Node not belong to model!"

**Comment by epsi1on** [comment]
This error means that at least one element is connected to a node, and that node is not in the `Model.Nodes` list.
You must find the node and add it into `Model.Nodes` with `Model.Nodes.Add`.

**Comment by epsi1on** [comment]
was you able to fix the issue with your code?

**Comment by MLiranzo** [comment]
Hi eps1on,
Unfortunately not yet, I have debugged my file, I do not have repeated nodes in the model.Nudes list, all nodes at the base have fixed supports, all triangle elements are correct, despite all that, I still have the nodes at the ends of the base of the wall with reactions equal to zero; that is, the intermediate nodes report reaction values.

**Comment by MLiranzo** [comment]
Hi eps1on,
Thanks for her suggestions, following her I was able to solve the error of my code. The problem was that the extreme nodes of the base of the wall, although they were introduced in the model.Nodes, were not referenced as a property of the walls. View image.
![image](https://user-images.githubusercontent.com/53960987/170766372-ca8c8de4-9733-4f11-96ff-1bfc47d8848e.png)

**Comment by epsi1on** [comment]
ok, so please close the issue if it is resolved

**Comment by MLiranzo** [comment]
Hola eps1on,
estoy tratando de obtener los esfuerzos en placas de concreto y obtengo la
excepción que se muestra en el gráfico. Utilizo los mismos conceptos y
directivas del Case_02 ejemplo de verificación propuesto en el paquete.

**Comment by MLiranzo** [comment]
Hi eps1on,
It is true, on that occasion I had problems obtaining the results of the reactions and that issue was solved, then I presented similar problems when I tried to obtain the stresses in plates, however the proposed solutions did not solve the problem and since then I have tried without success work it out.

**Comment by epsi1on** [comment]
> Hi eps1on, It is true, on that occasion I had problems obtaining the results of the reactions and that issue was solved, then I presented similar problems when I tried to obtain the stresses in plates, however the proposed solutions did not solve the problem and since then I have tried without success work it out.

https://engineering.stackexchange.com/q/11568
