### ISSUE TITLE
Exception when Trying to Gain Efforts in Triangular Element Shell.

### ISSUE THREAD

**Issue by MLiranzo** [BriefFiniteElementNet/BriefFiniteElement.Net#139]
Hi eps1on,
After solving my code problem related to reactions, in the following code snippet.
`int w = 0;
            for (int k = 0; k < lstCas.Count; k++)
            {
                lsEsfTot = new List<List<float>>();

                foreach (var telm in Telm)
                {
                    var element = telm as TriangleElement;
                    if (element == null) { continue; }

                    List<float> results = new List<float>();
                    var cauchy = element.GetInternalStress(new double[] { dx, 1, dz }, lstCas[k], SectionPoints.Envelope);

                    results.Add((float)cauchy.S11);
                    results.Add((float)cauchy.S12);
                    results.Add((float)cauchy.S13);
                    results.Add((float)cauchy.S21);
                    results.Add((float)cauchy.S22);
                    results.Add((float)cauchy.S23);
                    results.Add((float)cauchy.S31);
                    results.Add((float)cauchy.S32);
                    results.Add((float)cauchy.S32);
                    results.Add((float)w);
                    lsEsfTot.Add(results);
                    w++;
                }
                lstEsfTot.Add(lsEsfTot);
            }`
I get the following exception:
![mensaje](https://user-images.githubusercontent.com/53960987/170721434-ae4f825e-a1b4-412f-afff-ed300c9e02c9.png)

**Comment by epsi1on** [comment]
hi
This is not an error, its a feature of framework.
The reason is pretty much like your prior issues, where node or element not belong to the model.
It says the current `TriangleElement` (which you are trying to find its internal force) is not added to a model with `Mode.Elements.Add()` method. very much like the must bottom nodes of the shear wall (do you remember)?

**Comment by epsi1on** [comment]
closed due to inactivity
