### ISSUE TITLE
Exception in the Determination of Stress in plates.

### ISSUE THREAD

**Issue by MLiranzo** [BriefFiniteElementNet/BriefFiniteElement.Net#143]
Hi eps1on,
I am trying to obtain the Stress in concrete plates and I get the exception shown in the graph. I am using the same concepts and directives from the Verification Case_02 example proposed in the package.
![msgErr](https://user-images.githubusercontent.com/53960987/181310539-00f0c53b-0118-4095-bd54-0fb67cbc70bb.png)

**Comment by epsi1on** [comment]
put this before the yellow line:

`if(!(telm is TriangleElement)) continue;`

You are trying to cast `BarElement` into `TriangleElement` .

**Comment by MLiranzo** [comment]
Hi eps1on,
thanks for your prompt response, this part of my problem is solved.
