### ISSUE TITLE
Add Example With Different Elements, Beams, Columns and Plates or Shells are Integrated

### ISSUE THREAD

**Issue by MLiranzo** [BriefFiniteElementNet/BriefFiniteElement.Net#144]
Hi eps1on,
In a real structure the different elements, beams, columns and plates or shells are integrated, in few occasions an isolated plate is found. I make this initial comment to indicate the need to add an example of a structure where these different elements are integrated, preferably with two levels where the interaction between the plate of one level and another can be appreciated.
All this suggestion is made following my own experience. I have countless hours debugging a model with this characteristics and even though I have checked node by node and element by element and despite that I still get the same error. The result reports values ​​of deformation in the nodes and reports the values ​​of reactions in the nodes attached to the base.
I know that the topic related to this bug report that I made was closed some time ago, however, my problem continues, so I think that the best way to shed light is by making an example with a structure that has the characteristics mentioned above.

Thank You.

**Comment by epsi1on** [comment]
Hi,
You mean you have problem with a specific model?
If a model is failing to solve, then you can save the model into file (using `Model.Save()`) and put the file here.
Me or other users will check and reply...

**Comment by MLiranzo** [comment]
Hi eps1on,
I have not been able to send the model file through the implementation of Model.Save() because when trying to save the file the following exception occurs:
![Exception](https://user-images.githubusercontent.com/53960987/182384824-e47fa6b2-b597-4da4-851e-e98a19ede27c.png)

**Comment by epsi1on** [comment]
@MLiranzo Have a look at your prior post (you already had this issue)
https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/issues/135#issuecomment-1126988247

**Comment by MLiranzo** [comment]
Hi eps1on,
It is true, on that occasion I had problems obtaining the results of the reactions and that issue was solved, then I presented similar problems when I tried to obtain the stresses in plates, however the proposed solutions did not solve the problem and since then I have tried without success work it out.

**Comment by epsi1on** [comment]
To fix the "Node not belong to model" error you should do this:

Whenever you create a node like this `new Node()`, you should add the new node to the `Model.Nodes` collection.
I think if you fix the  "Node not belong to model", your other problem will also fix...

**Comment by MLiranzo** [comment]
Hi eps1on,
How the isoLocation arrays are expressed in Triangular elements, I see the example Case_02, where the following are presented: new double[] { 0.166666666, 0.1666666, 1.0 } and new double[] { 0.6666666, 0.1666666, 1.0 } and new double[ ] { 0.166666666, 0.6666666, 1.0 }, in the determination of the stresses.

**Comment by epsi1on** [comment]
inactivity
