### ISSUE TITLE
Status of shell elements

### ISSUE THREAD

**Issue by mluksevics** [BriefFiniteElementNet/BriefFiniteElement.Net#15]
Hello eps1lon, thank you for the great work on BFE.net!

I am trying to use shell elements to model plate with bending. 
Looks like TriangleElement is obsolete. Which shell element would be the "most developed" for it to use? I also tried using TriangleFlatShell but struggle to understand the way how the nodes of triangular element should be defined (propery Nodes is read only).

**Comment by epsi1on** [comment]
Hi, thanks.
Yes the ``TriangleFlatShell.Nodes`` property is readonly. You should set each member separately like this:

```
element.Nodes[0]= new Node(0,0,0);

element.Nodes[1]= new Node(1,0,0);

element.Nodes[2]= new Node(0,1,0);
```

**Comment by mluksevics** [comment]
Thank you eps1lon! That worked, now I am trying to figure out some instabilities and hope to have the model running this weekend.

**Comment by epsi1on** [comment]
Hi @mluksevics 
Was you able to run your model?
