### ISSUE TITLE
Add Master Node in  

### ISSUE THREAD

**Issue by MLiranzo** [BriefFiniteElementNet/BriefFiniteElement.Net#150]
Hello epsi1on,
Is there the possibility of creating a master node to the floors to add loads for floors, masses and others?
Thanks.

**Comment by epsi1on** [comment]
Hello,
What is the benefit? do you need MPC SPC element (like rigid link)?

**Comment by MLiranzo** [comment]
Hello epsi1on,
The objective of this Node would be a better distribution of the lateral loads and the possibility of directly applying torsion moment per story. Currently my project computes the forces and torsion per floor and the results are very good, however, in the distribution to the elements a lot is lost, especially in the cases of structures with panels (walls). The distribution of the forces to the panels is carried out according to the rigidity of the elements; however, the stiffness of frames when there are panels is a somewhat nebulous point because few methods address this issue clearly and the results are not so good. In the project I use the Shultz method to determine the rigidity of frames and although this method does not specify that it can be used when there are panels, I dare to use it, since I only use it to distribute the lateral loads per floor.

Thanks

**Comment by epsi1on** [comment]
Maybe RigidElement can work for you. ([link](https://bfenet.readthedocs.io/en/latest/elements/mpcelements/rigid/index.html)).
Just note that there are two classes of RigidElement, if you use the wrong one, then it throws exception. so you can change it. if it do not throws exception then it is good to go. [this example and documentation](https://www.codeproject.com/Articles/850733/RigidElements-in-BriefFiniteElement-NET) is relaterd to older version, but very similar to current one.

**Comment by epsi1on** [comment]
inactivity
