### ISSUE TITLE
Create a Trapezoidal Load on an Complete Element.

### ISSUE THREAD

**Issue by MLiranzo** [BriefFiniteElementNet/BriefFiniteElement.Net#151]
Hi.
It is possible to create a full trapezoidal load, that is, triangle-rectangle-triangle, without having to split the element according to the drawing shown below.
![load](https://user-images.githubusercontent.com/53960987/219497492-194ee83b-2faf-4bb5-89f6-eece0887884e.png)

Greeting 
M. Liranzo

**Comment by epsi1on** [comment]
Hi. 
There is no such load implemented yet as a single class. but you can use three PartialNonuniform load on a single element, also can have three separate elements.
it is also possible to create a new class which derives from `ElementalLoad` which is base class of all elemental loads, For example named TRTLoad (stand for triangle-rectangle-triangle Load).

**Comment by MLiranzo** [comment]
Thank You.
I will try to implement it follow your idea.

**Comment by epsi1on** [comment]
> Thank You. I will try to implement it follow your idea.

ok, pls. let me know if i can help.

**Comment by epsi1on** [comment]
inactivity
