### ISSUE TITLE
xml documentation not available in nuget package

### ISSUE THREAD

**Issue by devel0** [BriefFiniteElementNet/BriefFiniteElement.Net#155]
The nuget package doesn't provide intellisense support over library functions.

![image](https://user-images.githubusercontent.com/13405008/230618423-bfaccbf8-7eef-4197-ac33-cfaa696fe2e9.png)

It could enabled by changing [this line](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/blob/b7173d2e3ab8e3896f365d5f1c5ee0943a3d307d/Sources/BriefFiniteElementNet/BriefFiniteElementNet.csproj#L9) set to true.

**Comment by epsi1on** [comment]
Done, 
you can also suggest edits with making pull requests.
thanks

**Comment by devel0** [comment]
Thanks you.
