### ISSUE TITLE
Error message when trying to use WpfTraceListener.CreateModelTrace(model)

### ISSUE THREAD

**Issue by MLiranzo** [BriefFiniteElementNet/BriefFiniteElement.Net#159]
Hi epsi1on, when I try to use the methods to check the model.
var wnd = WpfTraceListener.CreateModelTrace(model);
             new ModelWarningChecker().CheckModel(model);
             wnd.ShowDialog();
the following error message occurs. The type or namespace 'Window' does not exist in the namespace 'System.Windows'(Are you missing an Assembly reference?). What will I be omitting?

**Comment by epsi1on** [comment]
Hi,
Is it a compile time error, or runtime error?
I think you need to add reference to these assemblies for your project:
- PresentationFramework
- PresentationCore
- WindowsBase
- System.xaml

have a look at [here](https://stackoverflow.com/a/33441726)


Or you could simply use ConsoleTraceListener instead.

**Comment by MLiranzo** [comment]
Thank you for your time,
I have complete all the assembled from the list. The following graphic file shows the last message.
![Messege](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/assets/53960987/29b07791-de21-4be7-9730-6b4a81aa85ca)

**Comment by epsi1on** [comment]
WpfTraceListener is inside `BriefFiniteElement.Controls` assembly, you should add refrence to that too

**Comment by MLiranzo** [comment]
Hi, after adding the Controls.Proj and placing a reference to it, I still get an error message. I don't know what I'm omitting.
![Messege1](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/assets/53960987/e87a07d0-d8f8-483e-95a3-651cd223dd29)

**Comment by epsi1on** [comment]
i dont tknow, maybe if you show rest of the code, can help you.
Maybe it is from using section, or reference to BFE and BFE.Common assembly.

**Comment by MLiranzo** [comment]
Hi, reviewing and following the track I notice that I do not have the Controls.dll library in any assembly, I downloaded all the files again; but the new download does not have it either. Perhaps the lack of this file is the cause of my problem.

**Comment by epsi1on** [comment]
you could also use the nuget package for bfe and controls libray

**Comment by MLiranzo** [comment]
Hi, i download the nuget package for bfe and  can not find the Controls.dll library.
Thank you

**Comment by epsi1on** [comment]
controls is inside different library
https://feed.nuget.org/packages/BriefFiniteElement.WpfControls

**Comment by epsi1on** [comment]
inactivity
