### ISSUE TITLE
Method to Convert Units

### ISSUE THREAD

**Issue by MLiranzo** [BriefFiniteElementNet/BriefFiniteElement.Net#173]
Hi epsi1on,
There is a method in the library to convert units, for example, from metric units to International or SI units.

**Comment by epsi1on** [comment]
Hi Dear,
Unfortunately the units in the library are fixed (length: meter, Force: Newton, Mass: Kg). But I think there are many unit libraries you can use in your code to convert units. Even if it is not a complicated feature, then I think you can kind of DIY it with a little piece of code.

**Comment by epsi1on** [comment]
for example if you are using WPF, then you can do it as a `IValueConverter` i think

**Comment by MLiranzo** [comment]
Good. Thank you.
