### ISSUE TITLE
Deformation/displacement

### ISSUE THREAD

**Issue by Aliturkisk** [BriefFiniteElementNet/BriefFiniteElement.Net#179]
Hi
How can I get the element deformation and node displacement?

**Comment by epsi1on** [comment]
`Node.GetDisplacement()` and `BarElement.GetInternalDisplacement()` methods

**Comment by Aliturkisk** [comment]
Thank you for your reply but the data is not correct. Can you implement this method "GetExactInternalDisplacementAt"?
 In internal force, the method contains Exact returns the correct result.

**Comment by epsi1on** [comment]
Yes you are right, the result from `GetInternalDisplacement()` are approx solutions. 
the `‍‍GetExactInternalDisplacementAt()` is way more complicated than `GetExactInternalForce()`. 
I can remember there was some challenge with it last time i tried. hovewer i made a label for it, if other users ask too, or you willing to contribute in theory/code, i'll try again...

**Comment by Aliturkisk** [comment]
Ok I can fund it. Also we can help in coding.

**Comment by epsi1on** [comment]
OK, good...
Please kindly provide this information:

1- Which elements do you need `‍‍GetExactInternalDisplacementAt()` method for?
2- That method is depended to applied loads too, so please give more info about what types of load (like distributed, concentrated, etc) are you applying on the element?

**Comment by Aliturkisk** [comment]
Let us start by 
1- Bar element.
2- Uniform load.

**Comment by epsi1on** [comment]
OK, it would be possible to do. Could you please send me an email to talk about details for funding this feature you need?

Thanks

**Comment by Aliturkisk** [comment]
Sent

**Comment by epsi1on** [comment]
Thanks
I did reply your mail. Could you please check your spam folder too for the response?

**Comment by Aliturkisk** [comment]
I reply any update

**Comment by epsi1on** [comment]
inactivity
