### ISSUE TITLE
Internal moments in a beam

### ISSUE THREAD

**Issue by SerGlushko** [BriefFiniteElementNet/BriefFiniteElement.Net#19]
**Describe the bug**
I have a simple beam on two supports that has a distributed load applied to it. The solution gives incorrect results.

**To Reproduce**
This is the code We've used and caused wrong result/ runtime error

```
var model = new Model();
model.Nodes.Add(new Node(0, 0, 0) { Label = "n1" });
model.Nodes.Add(new Node(6, 0, 0) { Label = "n2" });
model.Nodes["n1"].Constraints = Constraints.FixedDZ & Constraints.FixedDY & Constraints.FixedRX & Constraints.FixedRZ;
model.Nodes["n2"].Constraints = Constraints.MovementFixed;
model.Elements.Add(new BarElement(model.Nodes["n1"], model.Nodes["n2"]) { Label = "r1" });
(model.Elements["r1"] as BarElement).Section = new BriefFiniteElementNet.Sections.UniformGeometric1DSection(SectionGenerator.GetRectangularSection(0.01, 0.01));
(model.Elements["r1"] as BarElement).Material = BriefFiniteElementNet.Materials.UniformIsotropicMaterial.CreateFromYoungPoisson(210 * Math.Pow(10, 9), 0.3);
model.Elements["r1"].Loads.Add(new BriefFiniteElementNet.Loads.UniformLoad(LoadCase.DefaultLoadCase, new Vector(0, 0, 1), -10000, CoordinationSystem.Local));
model.Solve_MPC();

var iso = (model.Elements["r1"] as BarElement).LocalCoordsToIsoCoords(0.0001);
Console.WriteLine((model.Elements["r1"] as BarElement).GetExactInternalForceAt(iso[0], LoadCase.DefaultLoadCase).My.ToString());
for (int i = 1; i < 6; i++)
{
iso = (model.Elements["r1"] as BarElement).LocalCoordsToIsoCoords(i);
Console.WriteLine((model.Elements["r1"] as BarElement).GetExactInternalForceAt(iso[0], LoadCase.DefaultLoadCase).My.ToString());
}
iso = (model.Elements["r1"] as BarElement).LocalCoordsToIsoCoords(6 - 0.0001);
Console.WriteLine((model.Elements["r1"] as BarElement).GetExactInternalForceAt(iso[0], LoadCase.DefaultLoadCase).My.ToString());
Console.ReadKey();
```

**Expected behavior**
Every result along the beam has to be ~30kN less: near nodes it has to aim to zero, and in the middle it's supposed to be -45kN

**Additional context**
![image](https://user-images.githubusercontent.com/22731503/57804695-f9ec6e80-7763-11e9-80cb-5b0ab41dd7a5.png)

**Comment by epsi1on** [comment]
Hello,
Thanks for details. I've updated the code, and it should work fine now, can you please check with updated code again and let me know if problem still exists?

Thanks

**Comment by SerGlushko** [comment]
Thanks for a quick reply, I have tested on this example and a few other simple ones, now the moments are correct.
But it looks like I found another issue with the latest version: running exactly the same code as previously, but with GetInternalDisplacementAt instead of GetExactInternalForceAt gives inverted results compared to the results I got yesterday.

Previous version displacements:

![image](https://user-images.githubusercontent.com/22731503/57868305-65d5e200-780b-11e9-9346-a87fd3f991c0.png)

Current displacements:

![image](https://user-images.githubusercontent.com/22731503/57869690-3d9bb280-780e-11e9-8e1a-22fe82dceb19.png)

So the beam under load bends upwards instead of bending downwards.

**Comment by epsi1on** [comment]
Internal displacement is a little buggy now
should fix it soon

**Comment by epsi1on** [comment]
> 
> 
> Thanks for a quick reply, I have tested on this example and a few other simple ones, now the moments are correct.
> But it looks like I found another issue with the latest version: running exactly the same code as previously, but with GetInternalDisplacementAt instead of GetExactInternalForceAt gives inverted results compared to the results I got yesterday.
> 
> Previous version displacements:
> 
> ![image](https://user-images.githubusercontent.com/22731503/57868305-65d5e200-780b-11e9-9346-a87fd3f991c0.png)
> 
> Current displacements:
> 
> ![image](https://user-images.githubusercontent.com/22731503/57869690-3d9bb280-780e-11e9-8e1a-22fe82dceb19.png)
> 
> So the beam under load bends upwards instead of bending downwards.
> 
> UPD: It appears that internal force Fz is inverted too.

hi,
It is fixed now, can you please check with updated code please?

Thanks

**Comment by SerGlushko** [comment]
Thanks, looks like it's fine now
