### ISSUE TITLE
GetExactInternalForceAt(position).Mz Bug

### ISSUE THREAD

**Issue by luisggc** [BriefFiniteElementNet/BriefFiniteElement.Net#22]
**Describe the bug**
GetExactInternalForceAt(position).Mz doesn't return the right value, but GetSupportReaction() works nice.

```
               var model = new BriefFiniteElementNet.Model();

                var n1 = new Node(-1, 0, 0) { Label = "n1", Constraints = BriefFiniteElementNet.Constraints.MovementFixed & BriefFiniteElementNet.Constraints.FixedRX };

                var n2 = new Node(1, 0, 0) { Label = "n2", Constraints = BriefFiniteElementNet.Constraints.MovementFixed };

                var loadPositionX = 0;

                var e1 = new BarElement(n1, n2) { Label = "e1" };
e1.Section = new BriefFiniteElementNet.Sections.UniformGeometric1DSection(SectionGenerator.GetRectangularSection(0.1d, 0.2d));
            e1.Material = BriefFiniteElementNet.Materials.UniformIsotropicMaterial.CreateFromYoungPoisson(210e9, 0.3);
            model.Nodes.Add(n1, n2);
            model.Elements.Add(e1);
            var force = new Force(0, -1, 0, 0, 0, 0);
            var elementLoad = new BriefFiniteElementNet.Loads.ConcentratedLoad
            {
                CoordinationSystem = CoordinationSystem.Local,
                Force = force,
                ForceIsoLocation = new IsoPoint(loadPositionX)
            };
            e1.Loads.Add(elementLoad);
            model.Solve();
```

**Expected behavior**
Get momentum 0 when x = -0.99999999 or x=0.999999999

**Additional context**

When Load is in the middle (x=0):
![image](https://user-images.githubusercontent.com/31017690/64223117-03334f80-cea9-11e9-8550-3c20436d26fc.png)

When Load is in x=+0,5
![image](https://user-images.githubusercontent.com/31017690/64223088-eb5bcb80-cea8-11e9-86e5-b4a2c7e6bc21.png)

**Comment by epsi1on** [comment]
Thanks for detailed information.
Seems there is need to put more unit test for this type of load.
It is in progress...

**Comment by luisggc** [comment]
Thanks for your fast answer. Your work is fantastic!
Do you know if it's possible to have a Node which is not any kind of support? Haven't seem anything like that in the documentation. 

This way I could use the regular ponctual load on that node. We could also have distributed load in just a part of the beam.

**Comment by epsi1on** [comment]
Hi,
Code is updated. But please notice that you should use ``Element.GetExactInternalForce()`` instead of ``Element.GetInternalForce()`` if you use any element loads.

**Comment by epsi1on** [comment]
> 
> 
> Thanks for your fast answer. Your work is fantastic!
> Do you know if it's possible to have a Node which is not any kind of support? Haven't seem anything like that in the documentation.
> 
> This way I could use the regular ponctual load on that node. We could also have distributed load in just a part of the beam.

Yes distributed load on a part of beam is meant to be implemented in ``PartialNonuniformLoad`` file which is still under construction.
About node without any support, Yes that is possible (if I understand your question correctly, simply set ``Node.Constraints`` to ``Constraints.Released`` which is set by default).

**Comment by epsi1on** [comment]
I think problem is solved,
Can you please do check again?
Thanks

**Comment by epsi1on** [comment]
I think problem solved.
This is moment, when load is in middle:
![image](https://user-images.githubusercontent.com/7839141/66986438-cbd0d900-f0cb-11e9-8804-8fc407ea1afb.png)
This is moment, when load is in +0.5:
![image](https://user-images.githubusercontent.com/7839141/66986502-eacf6b00-f0cb-11e9-8002-aade354537f5.png)
