### ISSUE TITLE
Trapezoidal Load

### ISSUE THREAD

**Issue by epsi1on** [BriefFiniteElementNet/BriefFiniteElement.Net#25]
**Describe the bug**
Cannot solve with trapezoidal forces included.
``GetGlobalEquivalentNodalLoads()`` in helper classes is not implemented for PartialNonUniformLoad:

![image](https://user-images.githubusercontent.com/7839141/65935590-71c2e900-e426-11e9-849d-1a908e875fc3.png)

**To Reproduce**
Add a ``PartialNonUniformLoad`` into a ``BarElement.Loads``

**Expected behavior**
Code should run without throwing ``NotImplementedException``

**Additional context**
Reported by S.G.

**Comment by eykaraduman** [comment]
How can I use the severity function of `PartialNonUniformLoad()`? 
Or does this load type still contain bugs?

**Comment by epsi1on** [comment]
Hi,
Pls take a view here: #109 
Also note that `PartialNonUniformLoad`'s results is not validated yet.

**Comment by epsi1on** [comment]
I think resolved, check #111
