### ISSUE TITLE
Unexpected error based on element length

### ISSUE THREAD

**Issue by rkmore** [BriefFiniteElementNet/BriefFiniteElement.Net#28]
As always thank you for the most excellent library!!!

I have run across a strange problem where simply changing the length of an element causes the system to switch from correctly solving to throwing a “Matrix must be symmetric positive definite” exception.

It is very likely a "me" problem but I would love your insight as to why this is happening.

It is a simple cantilevered “PI” structure with hinged joints at the transverse arm attachment points (image is attached)

![PI](https://user-images.githubusercontent.com/3299954/68596701-9ff60880-0469-11ea-9f35-2aa5654ea4ce.png)

If you call the attached code with a cantelever length of 13 it works fine and at 14 it throws.

`            //runs (but results seem strange)
            PI(13);
            //Throws exception
            PI(14);

        private static void PI(double canteleverDist)
        {

            var model = new Model();

            Node Leg1Base = null;
            Node Leg1Tip = null;
            Node Leg2Base = null;
            Node Leg2Tip = null;

            for (int l = 1; l < 3; l++)
            {
                int x = -100 + (l - 1) * 200;
                Node LegBase = new Node(x, 0, 0) { Label = "Leg" + l.ToString() + "Base" };
                LegBase.Constraints = Constraints.Fixed;
                model.Nodes.Add(LegBase);
                var LegTip = new Node(x, 0, 400) { Label = "Leg" + l.ToString() + "Tip" };
                model.Nodes.Add(LegTip);
                var beam = MakeBeam(LegBase, LegTip, "Leg" + l.ToString());
                model.Elements.Add(beam);

                var n = new Node(x, canteleverDist, 400) { Label = "T" + l.ToString() };
                model.Nodes.Add(n);
                var offsetArm = MakeBeam(LegTip, n, "Offset" + l.ToString());
                model.Elements.Add(offsetArm);

                offsetArm.HingedAtEnd = true;

                LegTip = n;

                if (l < 2)
                {
                    Leg1Base = LegBase;
                    Leg1Tip = LegTip;
                }
                else
                {
                    Leg2Base = LegBase;
                    Leg2Tip = LegTip;
                }
            }

            var TopOverhangL = new Node(-150, 5, 350) { Label = "TopOverhang1" };
            var TopOverhangR = new Node(150, 5, 350) { Label = "TopOverhang2" };
            model.Nodes.Add(TopOverhangL);
            model.Nodes.Add(TopOverhangR);

            var TopCant1 = MakeBeam(TopOverhangL, Leg1Tip, "TopCant1");
            var TopBetweenLegs = MakeBeam(Leg1Tip, Leg2Tip, "TopBetweenLegs");
            var TopCant2 = MakeBeam(Leg2Tip, TopOverhangR, "TopCant2");
            model.Elements.Add(TopCant1);
            model.Elements.Add(TopBetweenLegs);
            model.Elements.Add(TopCant2);

            var force = new Force(100, 10, 10, 0, 0, 0);
            TopOverhangL.Loads.Add(new NodalLoad(force));

            force = new Force(-100, -10, -10, 0, 0, 0);
            TopOverhangR.Loads.Add(new NodalLoad(force));

            model.Solve();

            //var wnd = new Window();
            //var ctrl = new ModelVisualizerControl();
            //ctrl.ModelToVisualize = model;
            //wnd.Content = ctrl;
            //wnd.ShowDialog();

            var d = Leg1Tip.GetNodalDisplacement();
            Console.WriteLine("displacement on leg1 X: " + d.DX.ToString() + " Y: " + d.DY.ToString() + " Z: " + d.DZ.ToString());
            d = Leg2Tip.GetNodalDisplacement();
            Console.WriteLine("displacement on leg2 X: " + d.DX.ToString() + " Y: " + d.DY.ToString() + " Z: " + d.DZ.ToString());

        }

        private static FrameElement2Node MakeBeam(Node pN1, Node pN2, string pName)
        {
            var frameBeam = new FrameElement2Node(pN1, pN2);
            frameBeam.Label = pName;
            frameBeam.A = 116;
            frameBeam.Ay = 105;
            frameBeam.Az = 105;
            frameBeam.J = 408;
            frameBeam.Iy = 1080;
            frameBeam.Iz = 1080;
            frameBeam.E = 1660;
            frameBeam.G = 0.620;
            frameBeam.MassDensity = 0.3;
            frameBeam.MassFormulationType = MassFormulation.Consistent;
            return frameBeam;
        }
`
[Program.zip](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/files/3831892/Program.zip)

**Comment by epsi1on** [comment]
Hi,
seems the arm elements are hinged at one end:

   offsetArm.HingedAtEnd = true;

It looks statically unstable because arms can rotate freely, but am not sure why it do not give error with ``PI(13)`` and gives error with other number except 13...

**Comment by rkmore** [comment]
Thank you for your reply.

The hinge is by design as I don't want the bending load to transfer from the arm to the legs.  I am not sure I understand why this would be unstable as the arm should rotate about its long axis until the loads offset.

This is what I was modelling until I went down  bit of a rabbit chasing the problem and created the mode l I originally sent,

![pi](https://user-images.githubusercontent.com/3299954/68858416-fbff9d80-06b2-11ea-83e8-8d59271f6f25.jpg)

The arm need to be attached to the legs such that no twisting or bending transfers through the joint.  Is that now that a hinge joint would do?

I also tried modelling as bar elements and controlling the end releases that way but stil got the same result.

What would be the proper way to model something like this?

Thanks as always

**Comment by epsi1on** [comment]
I think what you are trying to do is geometric nonlinear analysis.
This library only can do linear analysis, which means effect of displacement in elements and nodes are so small that do not have any effect on geometry of structure.

Also in static analysis, if any node or DoF be possible to freely moves _(for_ example if a node is not connected to any element also not fixed to _ground)_ then this would make the stiffness matrix singular or at least anything other than positive definite, so you will get NotPosDef exception. Please keep in mind that no inertia or mass is considered in static analysis.

About the way you can model this structure with this library, i think you should remove the arms, and apply loads directly to the upper joint of arms (i mean exactly at red nodes in below image)
![image](https://user-images.githubusercontent.com/7839141/68918608-19e90300-0784-11ea-9f72-5b9e77324d6a.png)
As no moment is transferred through the arms, then you should only apply same loads on button joint

Another way is to consider a different model per each load, which orientation of arms are right along the direction of arms, so that no moment are transferred via arms. Also you should not hing any end of arms.

I think first way is simpler to do.

**Comment by rkmore** [comment]
Thank You!!!

I really appreciate your time and effort in providing the thorough explanation and the options to solve the original problem.

I can't stress enough how much your contribution to the community is appreciated byt me and (I am sure) many others.

Thank you again

RKM
