### ISSUE TITLE
PartialNonUniformLoad

### ISSUE THREAD

**Issue by peacelvirene** [BriefFiniteElementNet/BriefFiniteElement.Net#30]
Now the PartialNonUniformLoad is showed "still in development, have bugs", when will be done?
Thank you for your excellent project!

**Comment by epsi1on** [comment]
Cannot say a specific time, but I think you better check and validate it to see if it works and if works then return valid results or not, then use it.
Codes that are not validated successfully or lacking some features are marked as 'still in development, have bugs' that is not a compile error, but a warning.
Thanks

**Comment by peacelvirene** [comment]
Thanks!
The project is so complicated, I'm hardly studying it.

**Comment by epsi1on** [comment]
OK, if you encounter any other problem pls either create an issue or mail me, my email is in the profile @epsi1on
