### ISSUE TITLE
GetExactInternalDisplacementAt

### ISSUE THREAD

**Issue by peacelvirene** [BriefFiniteElementNet/BriefFiniteElement.Net#31]
The method GetExactInternalDisplacementAt is like this
```
        public Displacement GetExactInternalDisplacementAt(double xi)
        {
            throw new NotImplementedException();
        }
        #endregion
```
so it's still not done?
and the GetInternalDisplacementAt is to get the dispacement by the Local CoordinationSystem?

Now I want to draw the dispacement of the structure, how can I get the dispacement?

**Comment by epsi1on** [comment]
you should be able to get internal displacement with method ``GetInternalDisplacementAt`` method and that is in local coordination system. To convert it to global one, use like this:

    var xi = -0.5; //x = L/4
    var disp = barElement.GetInternalDisplacementAt(xi);
    var trMgr = barElement.GetTransformationManager();
    var global = trMgr.TransformLocalToGlobal(disp);

the ``GetExactInternalDisplacementAt()`` is not simple enough to implement. Maybe be deleted next...

**Comment by peacelvirene** [comment]
Thanks! I will.
