### ISSUE TITLE
Creating Mesh Analysis in Static/Material System

### ISSUE THREAD

**Issue by JajaRodriguez** [BriefFiniteElementNet/BriefFiniteElement.Net#32]
Hello. Is it possible to analyze by creating a mesh in the finite element method, I want to learn this.

The material identification section for 'Brief' is well described in the documentation section.

However, when material and material is defined, how can mesh analysis and discrete evaluation be performed for a static system?

'Brief' finds the moment diagram, shear forces, and support reactions very well in finite elements.

I want to use it also in mesh analysis? Could you help? Or, is it possible to add mesh example in documentation?

**Comment by epsi1on** [comment]
Hi,
By meshing do you mean the process of turning an area or volume into pieces?

**Comment by JajaRodriguez** [comment]
Is it possible to publish an example related to Delaunay Triangulation?

**Comment by epsi1on** [comment]
yes, I'll try to do

**Comment by JajaRodriguez** [comment]
> yes, I'll try to do

Thanks. I'll wait for the instance
