### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by peacelvirene** [BriefFiniteElementNet/BriefFiniteElement.Net#33]
## 1. About coordinate system
My interpretation of the coordinate system is like this image
And the disp is positive if the disp's direction  is the same as that of the coordinate axis.
 it's correct?
And how to judge a force is positive or negative?
![image](https://user-images.githubusercontent.com/41902864/75020496-d3ffb180-54cd-11ea-872b-bf7b9bba92e9.png)

## 2. About the unit
The unit is m for length and N for force?

## 3. About the UniformGeometric1DSection
The UniformGeometric1DSection is so easy for use!
I improved the GetCrossSectionPropertiesAt method like this
```
        public override _1DCrossSectionGeometricProperties GetCrossSectionPropertiesAt(double xi)
        {
            var buf = new _1DCrossSectionGeometricProperties();

            {
                var lastPoint = this._geometry[this._geometry.Length - 1];

                if (lastPoint != _geometry[0])
                    throw new InvalidOperationException("First point and last point ot PolygonYz should put on each other");

                double a = 0, iy = 0, iz = 0, ixy = 0, sy = 0, sz = 0, yc = 0, zc = 0;

                var x = new double[this._geometry.Length];
                var y = new double[this._geometry.Length];

                for (int i = 0; i < _geometry.Length; i++)
                {
                    x[i] = _geometry[i].Y;
                    y[i] = _geometry[i].Z;
                }

                var l = _geometry.Length - 1;
                for (var i = 0; i < l; i++)
                {
                    a += (x[i] - x[i + 1]) * (y[i] + y[i + 1]) / 2.0;
                    iy += (y[i] * y[i] + y[i + 1] * y[i + 1]) * (x[i] - x[i + 1]) * (y[i] + y[i + 1]) / 12.0;
                    iz += (x[i] * x[i] + x[i + 1] * x[i + 1]) * (y[i + 1] - y[i]) * (x[i] + x[i + 1]) / 12.0;
                    ixy += (iy + iz);
                    sy += (x[i] - x[i + 1]) * (y[i] * y[i] + y[i] * y[i + 1] + y[i + 1] * y[i + 1]) / 6;
                    sz += -(y[i] - y[i + 1]) * (x[i] * x[i] + x[i] * x[i + 1] + x[i + 1] * x[i + 1]) / 6;
                }
                yc = sz / a;
                zc = sy / a;
                //if the base axis is not the centroid axis, all the point need move
                if (Math.Abs(yc) > 0.00001 || Math.Abs(zc) > 0.00001)
                {
                    for (int i = 0; i < _geometry.Length; i++)
                    {
                        x[i] = _geometry[i].Y - yc;
                        y[i] = _geometry[i].Z - zc;
                    }
                    iy = 0;
                    iz = 0;
                    ixy = 0;
                    for (var i = 0; i < l; i++)
                    {
                        iy += (y[i] * y[i] + y[i + 1] * y[i + 1]) * (x[i] - x[i + 1]) * (y[i] + y[i + 1]) / 12.0;
                        iz += (x[i] * x[i] + x[i + 1] * x[i + 1]) * (y[i + 1] - y[i]) * (x[i] + x[i + 1]) / 12.0;
                        ixy += (iy + iz);
                    }
                }
               

                buf.A = Math.Abs(a);
                buf.Iz = Math.Abs(iz);
                buf.Iy = Math.Abs(iy);
                buf.J = Math.Abs(ixy);
                buf.Ay = Math.Abs(a);//TODO: Ay is not equal to A, this is temporary fix
                buf.Az = Math.Abs(a);//TODO: Az is not equal to A, this is temporary fix
            }

            return buf;
        }
```
The new method will cal the location of the centroid axis. So almost all section will be supportted.
TIP:Why the method need the param double xi?

## 4. About PartialNonUniformLoad
It's so hard to deal with the PartialNonUniformLoad. The BriefFiniteElement is a huge project.
Now  I deal with it like this way.
I add node nodes according to the load, and use uniformLoad in element to simulate the partialUniformLoad. Like this image, and the result is satisfying.
![image](https://user-images.githubusercontent.com/41902864/75021801-f397d980-54cf-11ea-92bd-ed4e7c6b96b4.png)

## 5.Thank you
Thank you for developing such an excellent project!

**Comment by epsi1on** [comment]
Hi,
1. Coordination System: yes seems it is right. Note that if element length be in X direction (e.g. element is parallel to X axis then global and local coordination system are same. in file `BarElement.cs` ln# 363 uses `CalcUtil.GetBarTransformationMatrix(Vector v, double webRotation=0)` for calculating the transformation matrix (transpose of lambda matrix) that is used for conversion between local and global coordination system.
2. yes, default units is meant to be the SI ones (Meter, Newton, Kg, etc.)
3. Can you please make it as a pull request?
4. `PartialNonuniformLoad` is sort of complicated and you are right. also this is not completely finished yet.
5. :)

**Comment by peacelvirene** [comment]
I'm not good at the Github, and I tried it.
Please tell me if my operation is wrong.

**Comment by epsi1on** [comment]
It should be right, I've done some minor changes in your code and merged it to master branch stuff.
Thanks
