### ISSUE TITLE
Add element force

### ISSUE THREAD

**Issue by peacelvirene** [BriefFiniteElementNet/BriefFiniteElement.Net#35]
Hi, epsi1on, how to add these types of element forces?
![image](https://user-images.githubusercontent.com/41902864/76053222-8001cc00-5fa7-11ea-8b40-cc04d3383b66.png)
for type C，I add like this
```
var u1 = new BriefFiniteElementNet.Loads.UniformLoad(
    LoadCase.DefaultLoadCase,
    -BriefFiniteElementNet.Vector.K,
    elmForce.QZ1 * 1000,
    CoordinationSystem.Global);
elm.Loads.Add(u1);
```
for type B, I add like this
```
var u1 = new BriefFiniteElementNet.Loads.UniformLoad(
    LoadCase.DefaultLoadCase,
    -BriefFiniteElementNet.Vector.K,
    elmForce.QZ1 * 1000,
    CoordinationSystem.Local);
elm.Loads.Add(u1);
```

that' right? and how to add the type A ?

**Comment by epsi1on** [comment]
Hi,
I've updated the example on documentation:
https://bfenet.readthedocs.io/en/latest/example/UniformLoadCoordSystem/index.html

there is third example where is same as your A case (that site is cached, you may need to clean browser cache to see third example)

**Comment by peacelvirene** [comment]
thanks!
