### ISSUE TITLE
Polar Area Moment Of Inertia

### ISSUE THREAD

**Issue by radiohalo123** [BriefFiniteElementNet/BriefFiniteElement.Net#38]
The most recent version of the code removes the ability to add custom J (Polar Area Moment Of Inertia) to a section and instead uses J = Iz + Iy.

I believe being able to enter a custom value for J would help users design structures with different cross sections accurately.

![image](https://user-images.githubusercontent.com/17434716/80101480-77595b00-853f-11ea-9877-22124c5f6fc4.png)

**Comment by epsi1on** [comment]
From [Torsion Constant on Wikipedia](https://en.wikipedia.org/wiki/Torsion_constant#cite_note-1):

In 1820, the French engineer A. Duleau derived analytically that the torsion constant of a beam is identical to the second moment of area normal to the section Jzz, which has an exact analytic equation, by assuming that a plane section before twisting remains planar after twisting, and a diameter remains a straight line. Unfortunately, that assumption is correct only in beams with circular cross-sections, and is incorrect for any other shape where warping takes place.

 Archie Higdon et al. "Mechanics of Materials, 4th edition"

**Comment by epsi1on** [comment]
Fixed in commit  9de50423

**Comment by ArtemRash** [comment]
It is very interesting to solve the problem of torsion constants determining
(https://www.researchgate.net/publication/225387731_Warping_shear_stresses_in_nonuniform_torsion_by_BEM for example)

**Comment by ArtemRash** [comment]
> > It is very interesting to solve the problem of torsion constants determining
> > (https://www.researchgate.net/publication/225387731_Warping_shear_stresses_in_nonuniform_torsion_by_BEM for example)
> 
> Is there any simpler method?

I'm afraid not. A simpler method is to determine the torsion constants "It" based on standard formulas (see earlier, for example). These formulas, unfortunately, apply only to individual cross-sectional shapes. The universal method is nontrivial.
