### ISSUE TITLE
GetInternalForce from TriangleFlatShell

### ISSUE THREAD

**Issue by slcver** [BriefFiniteElementNet/BriefFiniteElement.Net#39]
hi, how can i calculate stress (.GetInternalForce) for TriangleFlatShell elements after loading the Z direction? that s all be zero. (S11,S12, ... S33 = 0)
my code:

```
var model = new Model();

Node n0 = new Node(1, 4, 0);
n0.Label = "n0";

Node n1 = new Node(0, 4, 0);
n1.Label = "n1";

Node n2 = new Node(2, 4, 0);
n2.Label = "n2";

Node n3 = new Node(0, 0, 0);
n3.Label = "n3";

Node n4 = new Node(2, 0, 0);
n4.Label = "n4";

model.Nodes.Add(n0);
model.Nodes.Add(n1);
model.Nodes.Add(n2);
model.Nodes.Add(n3);
model.Nodes.Add(n4);

var ee = 3e7; // elastisite modulu 
var nu = 0.20;  //poissons ratio
var t = 0.20;  

TriangleFlatShell tr0 = new TriangleFlatShell();
tr0.Label = "tr0";
tr0.Behavior = FlatShellBehaviours.FullThinShell;
tr0.Nodes[0] = n0; 
tr0.Nodes[1] = n1; 
tr0.Nodes[2] = n3; 
tr0.PoissonRatio = nu;
tr0.ElasticModulus = ee;
tr0.Thickness = t;

TriangleFlatShell tr1 = new TriangleFlatShell();
tr1.Label = "tr1";
tr1.Behavior = FlatShellBehaviours.FullThinShell;
tr1.Nodes[0] = n3;
tr1.Nodes[1] = n4; 
tr1.Nodes[2] = n0; 
tr1.PoissonRatio = nu;
tr1.ElasticModulus = ee;
tr1.Thickness = t;

TriangleFlatShell tr2 = new TriangleFlatShell();
tr2.Label = "tr2";
tr2.Behavior = FlatShellBehaviours.FullThinShell;
tr2.Nodes[0] = n0; 
tr2.Nodes[1] = n2; 
tr2.Nodes[2] = n4; 
tr2.PoissonRatio = nu;
tr2.ElasticModulus = ee;
tr2.Thickness = t;

model.Elements.Add(tr0);
model.Elements.Add(tr1);
model.Elements.Add(tr2);

n3.Constraints = Constraints.Fixed;
n4.Constraints = Constraints.Fixed;

//var newCns = new Constraint(DofConstraint.Fixed, DofConstraint.Fixed, DofConstraint.Released,
//                            DofConstraint.Released, DofConstraint.Released, DofConstraint.Fixed);

//n0.Constraints = newCns;
//n1.Constraints = newCns;
//n2.Constraints = newCns;

n0.Constraints = Constraints.FixedDX;
n0.Constraints = Constraints.FixedDY;
n0.Constraints = Constraints.FixedRZ;

n1.Constraints = Constraints.FixedDX;
n1.Constraints = Constraints.FixedDY;
n1.Constraints = Constraints.FixedRZ;

n2.Constraints = Constraints.FixedDX;
n2.Constraints = Constraints.FixedDY;
n2.Constraints = Constraints.FixedRZ;

LoadCase d_case = new LoadCase();
d_case.CaseName = "d1";
d_case.LoadType = LoadType.Dead;

UniformLoadForPlanarElements f1_planerLoad = new UniformLoadForPlanarElements();
f1_planerLoad.Case = d_case;
f1_planerLoad.Ux = 0;
f1_planerLoad.Uy = 0;
f1_planerLoad.Uz = -1000;
f1_planerLoad.CoordinationSystem = CoordinationSystem.Global;

tr1.Loads.Add(f1_planerLoad);

LoadCombination comb1 = new LoadCombination(); 
comb1.Add(d_case, 1);

model.Solve_MPC(); 

var dep0 = n0.GetNodalDisplacement(comb1);
var dep1 = n1.GetNodalDisplacement(comb1);
var dep2 = n2.GetNodalDisplacement(comb1);
var dep3 = n3.GetNodalDisplacement(comb1);
var dep4 = n4.GetNodalDisplacement(comb1);

var s0 = tr0.GetInternalForce(0, 0, comb1);
var s1 = tr1.GetInternalForce(0, 0, comb1);
var s2 = tr2.GetInternalForce(0, 0, comb1);

var r0 = n0.GetSupportReaction(comb1);
var r1 = n1.GetSupportReaction(comb1);
var r2 = n2.GetSupportReaction(comb1);
var r3 = n3.GetSupportReaction(comb1);
var r4 = n4.GetSupportReaction(comb1);
```

**Comment by epsi1on** [comment]
Hello,
Have you checked the [UniformLoad](https://bfenet.readthedocs.io/en/latest/loads/elementLoads/uniformload.html) instead of UniformLoadForPlanarElements?

**Comment by slcver** [comment]
Hello,
yes i have checked the UniformLoad. This time, however, if I use the Load Combination or Load Case type, the following lines will generate a **System.NotImplementedException** error.

```
var dep1 = n1.GetNodalDisplacement(comb1);
...
var s0 = tr0.GetInternalForce(0, 0, comb1);
...
var r0 = n0.GetSupportReaction(comb1);
...
```

**Comment by epsi1on** [comment]
Yes you are right, my mistake.
Actually there are two methods for finding internal force in BFE, i call first one `GetInternalForce` and second one `GetExactInternalForce`. First one uses the standard finite element formula for internal force which is:
 `F = D*B*U`

- D: Constitutive matrix (`m x m` matrix)
- B: Consistency matrix (`m x m` matrix)
- U: displacement vector (`m x 1` matrix)

Where `m` is related to count of element's nodes. As `U` which is displacement vector is zero then regardless the values of `B` and `D` matrix, you always get zero as internal force.

The second method `GetExactInternalForce` takes the uniform load effect into account, which will makes the nonzero internal force. But this method is not implemented for `TriangleFlatShell`. 
For example take a look at [BarElement internal force](https://bfenet.readthedocs.io/en/latest/elements/finiteElements/Bar/internalforces.html) to see difference for BarElement.

`TriangleElement` is going to be successor for other triangular elements, so `GetExactInternalForce` will be implemented for `TriangleElement` in unknown future.

**Comment by epsi1on** [comment]
Also need to note that currently lumped approach is used for converting surface load of triangle elements into equivalent nodal loads, so no nodal moments are created when uniform load is converted to equivalent nodal loads

**Comment by slcver** [comment]
Thanks for your answers. But if I use the nodal force in the Z direction or nodal moment, I can't calculate the stress again (.GetInternalForce) (S11,S12, ... S33 = 0). I think problem is nothing uniform load, as you mentioned in your previous message 

Does Quadrilateral elements have such a problem? Maybe you should concentrate your studies on Quadrilateral elements...

**Comment by epsi1on** [comment]
If you use 4 triangle elements instead of one (total nodes will be 6 nodes, which 3 are fixed) then it should be fine.

**Comment by epsi1on** [comment]
Please also note `TriangleFlatShell ` is deprecated now, and you better use `TriangleElement` instead
