### ISSUE TITLE
CSparse does not install correctly with VS Community 2017

### ISSUE THREAD

**Issue by Pipeliner** [BriefFiniteElementNet/BriefFiniteElement.Net#42]
**Describe the bug**
I tried to follow https://bfenet.readthedocs.io/en/latest/gettingstarted/index.html.
The BriefFiniteElementNet.Common projects does not build due to a broken reference to CSparse.

**Expected behavior**
CSparse reference works correctly after adding the two mentioned `.csproj` files in a new solution.

**Workaround**
Deleting the broken CSparse reference and manually adding a new one to `packages/CSparse.3.4.2/lib/net40/CSparse.dll` helps.

```diff
-      <HintPath>..\packages\CSparse.3.4.2\lib\net40\CSparse.dll</HintPath>
+      <HintPath>..\..\packages\CSparse.3.4.2\lib\net40\CSparse.dll</HintPath>
`

**Comment by thaletob** [comment]
I had the same problem, it works now correcty after adding the latest .csproj-file of CSparse to the VS project.

**Comment by epsi1on** [comment]
Hi,
Thanks for reporting this issue, Compiling is done without problem with VS2019 Community Edition, but seems have problem with nuget packages in VS2017 as reported on this issue. 
I also added hyperlink to this issue on documentation in readthedocs changes will be applied soon.
