### ISSUE TITLE
Adding new Elements

### ISSUE THREAD

**Issue by thaletob** [BriefFiniteElementNet/BriefFiniteElement.Net#43]
Hello there,
first of all I need to thank you for this great work. I actually need to implement a four-noded rectangular element to your library. Have you got any special hints or things I need to consider because I'm a relatively new BFE.Net-user but familiar with FEM. 
Thank you!

**Comment by epsi1on** [comment]
Hi,
You are welcome...
What behaviors do you need for new rectangular element? 
Example behaviors are membrane, plate bending (thin or thick) etc.
There should be a `QuadrilaturalElement` class, also several `ElementHelpers`, once you tell me which behavior do you need, I'll add the classes.
Thanks

**Comment by thaletob** [comment]
Hi there,
thanks for the quick response. I already had a look at the Triangle-Element class and I'm planning to keep it as similar as possible. Well in this special case I want to create a 2D-model of quadratic elements with a 3d-loadcase. So it's more behaving like a thin plate then a membrane (because of the 3d loads). 
I appreciate any feedback/ hints you might have!

**Comment by epsi1on** [comment]
Hi,
I think adding new element is not hard. The current design pattern and in BFE.NET is like this: Element class is just a holder of state and common properties of elements and math calculations (like integrating Bt*D*B or integrating the body loads) are implemented in helper classes. Also keep in mind that BFE is only linear analysis yet.
So first thing is to create empty classes:

`BriefFiniteElementNet.Elements.QuadrilaturalElement` inherits from `Element`

`BriefFiniteElementNet.ElementHelpers.DkqHelper` (for plate bending) inherits from `ElementHelper` class.

**Comment by epsi1on** [comment]
I've added related project to the projects section 

https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/projects/1

Also i did some implementations earlier, i should do so checks.

**Comment by epsi1on** [comment]
This is also a good reference:
`Development of Membrane, Plate and Flat Shell Elements in Java` by Kaushalkumar Kansara:

https://pdfs.semanticscholar.org/581b/ea64790f0162cee58977edc747f489592a90.pdf

**Comment by thaletob** [comment]
Hey, I will try this the following weeks. Linear analysis is all I need so far. 
And thank you for the document, at the first view it seems to be very helpful!

You said you did some implementations earlier, what do you mean? 
Greetings!

**Comment by thaletob** [comment]
I actually created the blank classes, what can I do with the project (QuadrilaturalElement) you added in the projects section?

**Comment by epsi1on** [comment]
Hi,
If you plan to add this quad element into this library then definitely I will help.
I did code quad element (membrane and plate bending) maybe a year ago for someone, but that is not consistent with this current `ElementHelper` and `Element` pattern, so i would like to upgrade it...

**Comment by thaletob** [comment]
Hey, yes I'm planning to add it. I really need it for a still running project of topology optimizing structures in aero engines. 
Thank you very much for this offer! I think we should keep in touch here.
Greetings!

**Comment by epsi1on** [comment]
OK,
i did also add them into `BriefFiniteElementNet.CustomElements/Elements/` project, Next step is to implement IElementHelper mehtods, There are three helper classes:

DkqHelper
Q4MembraneHelper
Q4BasicDrillingDofHelper

Each one a .cs file (source code) amd a .md file (for documentation).

![image](https://user-images.githubusercontent.com/7839141/83355812-faf43c00-a376-11ea-912f-93d6c5fc632a.png)

Q4MembraneHelper is like `CstHelper.cs` class. `DkqHelper`is like `DktHelper.cs` and `TriangleBasicDrillingDofHelper` is like `QuadBasicDrillingDofHelper.cs`.
Also methods are somehow nicely commented in `IElementHelper.cs` file and `Element.cs` file.

**Comment by epsi1on** [comment]
I think you should use pull request to main github repository in order to both of us work on same code and can keep each other updated with code.

**Comment by thaletob** [comment]
Thank you for adding the first files to the project. Unfortunately I have not found any time to continue the work this week. I will try to continue next week. 
Somehow I cannot create a new pull request so far.

**Comment by thaletob** [comment]
I think adding a pull request is not possible because of missing rights. Maybe you could create a pull request where we could share our code.

**Comment by epsi1on** [comment]
I think for creating pull request there is no special permission to the GitHub repository. For merging there is need for permission.

Thanks

**Comment by epsi1on** [comment]
Hi,

> You simply copied the TriangleElement-Class into QuadrilateralElement-Class at the beginning, right?

No i just copied the common part of those elements. Maybe some renaming are required...

**Comment by thaletob** [comment]
Thank you! I'll keep you updated.

**Comment by epsi1on** [comment]
Hi,
Merged your pullrequest

**Comment by thaletob** [comment]
Thank you! I hope the bahaviour-classes were correct.

**Comment by thaletob** [comment]
If I understood correctly, I only have to add the tree classes (DkqHelper, QUadBasicDrillingDofHelper and Q4MembraneHelper) now to get the Element finished, right?

**Comment by epsi1on** [comment]
yes, then should do tests and on successful test, yes finish

**Comment by thaletob** [comment]
Great! Can you name your source for the matrix-calculations in the Helper-Methods? This could save some time actually.

**Comment by epsi1on** [comment]
> 
> 
> Great! Can you name your source for the matrix-calculations in the Helper-Methods? This could save some time actually.

You can have a look at similar helpers, for example `Cst (constant stress/strain triangle)` is similar to `QuadMembrane` etc. What you mean by matrix calculations?

**Comment by thaletob** [comment]
With Matric-Calculations I mean functions like: CalcLocalStiffnessMatrix, GetBMatrixAt, CalcLocalKMatrix_Triangle, etc.

**Comment by epsi1on** [comment]
this could be good resource:
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.619.9320&rep=rep1&type=pdf

also DktHelper.md file have some links for implementations of DKT, maybe implementations of DKQ or Q4 would be found there

**Comment by thaletob** [comment]
Thank you, yes I already checked out these links in DKtHelper.md but without finding good results.

**Comment by epsi1on** [comment]
These two are good too:

https://github.com/DBorello/OpenSees/blob/master/SRC/element/shell/ShellDKGQ.cpp
http://what-when-how.com/the-finite-element-method/fem-for-two-dimensional-solids-finite-element-method-part-2/

**Comment by thaletob** [comment]
Cool! I also found the right formulas in the PDF file that you've sent.

**Comment by epsi1on** [comment]
these two are good too

http://opensees.berkeley.edu/WebSVN/filedetails.php?repname=OpenSees&path=%2Ftrunk%2FSRC%2Felement%2Fshell%2FShellNLDKGQ.cpp&rev=5995
http://www.luxinzheng.net/publication7/2017-JEE-DKGQ_OpenSees.htm


[DkqHelper.zip](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/files/4757301/DkqHelper.zip)

this one also maybe help

**Comment by epsi1on** [comment]
Also please note that put the references in each helper file (for example documentation file for 'DkqHelper.cs' is 'DkqHelper.md'

thanks

**Comment by thaletob** [comment]
I will do that. Fortunately I'm using the same refs as you did before (e.g. "Development of Membrane, Plate and Flat Shell Elements in Java").

**Comment by epsi1on** [comment]
Do you have any reference for shape function of dkq element? i mean `DkqHelper.GetNMatrixAt()` method.

shape function is used in calculating equivalent nodal loads and internal displacements
both of these should takes the nodal rotations into account.
as DKQ have 12 DoF, shape function matrix should be 12 column matrix, but currently it is 4 columned matrix

**Comment by epsi1on** [comment]
I stuck with this shape function sometime ago

**Comment by thaletob** [comment]
It needs to be verified, because at this point I took your suggested DQT-file. I just did some little changes, but no changes in the calcluation. It might be a mistake in this code.

**Comment by thaletob** [comment]
I just checked one of the functions there which was okay. I did not check all of them because of missing time.

**Comment by epsi1on** [comment]
DkqHelper still need to implement `GetEquivalentNodalLoads()` for `PartialNonuniformLoad`. Not so important, so can be done later.

**Comment by thaletob** [comment]
Okay, and it is also refering to a DistributedNonUniformLoad (line 551) which is not existing yet.
Actually I did start with adding the calculations for Q4MembraneHelper.

**Comment by thaletob** [comment]
Okay we are talking about the same thing, I see you already changed the names

**Comment by epsi1on** [comment]
@thaletob I think there is a problem with `Q4MembraneHelper.GetBMatrixAt()` which returns zero.
I've updated the `QuadElementTester` with three different method for each behavior
Please just note that there should not be any "non positive" elements on main diagonal of stiffness matrix returned from `IElementHelper.CalcLocalStiffnessMatrix()' otherwise there will be an error. Any "non positive" (for example zero or negative value) member on main diagonal, if do not constrained correctly, will cause stiffness matrix to be NOT positive definite and that is not correct, at least i did not see any non positive definite stiffness matrix in linear analysis that be result of a correct calculation.

**Comment by thaletob** [comment]
Thank you for your effort. I think I found at least one mistake. Matrix B consists of Matrix A and Matrix G. Matrix A seems to be correct, but Matrix G returned 0. I found out, that one factor within `GetGMatrix,` which I declared as q = (1 / 4) was interpreted as 0, that is why each member of the Matrix was multiplied by 0. I changed it to q = 0.25 . Now Matrix G is not empty which results in Matrix B beeing not empty too. There is no error left now. I just need to compare the result of the calculation for now :)

**Comment by thaletob** [comment]
#59

**Comment by thaletob** [comment]
Which units are you using within the calculations? (for E-Modulus, Forces, etc.) Just to be consitent to that.

**Comment by rubsy92** [comment]
It's unit-less - so you can SI (N, m, Pa,...)

**Comment by thaletob** [comment]
@rubsy92 Thanks

**Comment by epsi1on** [comment]
@thaletob Can you please see the pull request #61 , a little code is changed in `Q4MembraneHelper.cs`, can you please do a review?
Thanks

**Comment by thaletob** [comment]
Seems to be okay! He found one mistake in my code and then he added a second digit after the decimal in most cases.

**Comment by rubsy92** [comment]
@thaletob  could you double-check the GetBMatrixAt-method in DKQ helper? At a first glance it looks a bit funny. Thanks!

**Comment by thaletob** [comment]
You are right, it really looks a bit funny. I checked the function, is is directly refering to the "Development of [...] Elements in Java"-PDF that you've sent before. Just some letters are changed compared to the given formulas. So in my opinion it is okay, I just did some little cosmetical changes within #62 .

**Comment by rubsy92** [comment]
@thaletob I checked it and it seems to be okay indeed. However my bending-validation indicates that the element is not stiff enough. It's about 10% off in some cases...

**Comment by thaletob** [comment]
Okay!

**Comment by thaletob** [comment]
@epsi1on Is there any possibility (already implemented) to gather elemental stresses ? Otherwise I'm going to implement it. Best regards and thank you for the help so far!

**Comment by rubsy92** [comment]
Hi @thaletob ,

I implemented it for the triangleElement (see the FlatShellStressTensor GetInternalStress(double localX, double localY, double localZ, LoadCombination combination, SectionPoints probeLocation) method). I also implemented it for the quadrilateral element, but I need to create a pull request. 

Ps have you already tried to validate the quadrilateral element?

**Comment by thaletob** [comment]
Hi, I hope you will create the pull request, because this is exactly what I was planning for the quad-Element. 
I did not continue validating yet @rubsy92 .

**Comment by rubsy92** [comment]
@thaletob  It's already created. Needs to be approved or you can check out the code in the pull-request section.

**Comment by thaletob** [comment]
@rubsy92 Alright!

**Comment by epsi1on** [comment]
Hi,
There are two approaches for getting internal force of either `TriangleElement` and `QuadrilaturalElement`.
- Consider effect of bending on the Cauchy stress through the thickness of plate, in this case return type is single `CauchyStressTensor` instance
- Do not consider effect of bending on the Cauchy stress, this case return type is `GeneralStressTensor` instance where consist of a `CauchyStressTensor` and a `BendingStressTensor`.

```
public struct GeneralStressTensor
{
    public CauchyStressTensor MembraneTensor;
    public BendingStressTensor BendingTensor;
}
```
Which one do you prefer?
I think first approach is better

**Comment by thaletob** [comment]
I really prefer the first approach.

**Comment by epsi1on** [comment]
> I really prefer the first approach.

I think only method that needs to be changed is `QuadElement.GetInternalStress` method. I think this exactly is what @rubsy92 implemented, Also sorry for delay, I'll try to check the pull request today ...

Thanks

**Comment by thaletob** [comment]
Yes, I also saw this. This is great.
Thank you.

**Comment by thaletob** [comment]
@epsi1on Did you already find some time to check the pull request #64 ?

**Comment by epsi1on** [comment]
> 
> 
> @epsi1on Did you already find some time to check the pull request #64 ?

Yes, that is merged

**Comment by thaletob** [comment]
Great! Thank you!


Zitat von epsi1on <notifications@github.com>:

**Comment by epsi1on** [comment]
There are several thing to do.
How can one convert uniform load into equivalent nodal loads for triangle or q4 element? We should do it for triangle and q4 elements.

**Comment by thaletob** [comment]
@epsi1on This is right. But I think I'm not having much time to do this during the following weeks.

**Comment by epsi1on** [comment]
Hi,
Are you sure about the formula inside this method:

``` 
 public CauchyStressTensor ConvertBendingStressToCauchyTensor(double shellThickness)
        {
            CauchyStressTensor cauchyStressTensor = new CauchyStressTensor();
            cauchyStressTensor.S11 = this.M11 * 6 / Math.Pow(shellThickness, 2);
            cauchyStressTensor.S22 = this.M22 * 6 / Math.Pow(shellThickness, 2);
            cauchyStressTensor.S12 = this.M12 * 6 / Math.Pow(shellThickness, 2);
            cauchyStressTensor.S21 = this.M21 * 6 / Math.Pow(shellThickness, 2);
            //all other components are 0 since it is a shell according to Kirchoff plate theory -> no 3-components!
            return cauchyStressTensor;
        }
```
In this formula if someone wants to input middle of section (z=0) then it cause divide by zero exception. Do you know any other formulas for this conversion?

Thanks

**Comment by rubsy92** [comment]
Hi, 

The formula should be correct; I verified it on the top/bottom surface with Abaqus. However, a check should be added to see if shellthickness==0 (which means that you are extracting the stress at the mid-fibre of the shell). This will result in zero stress due to bending, so an empty/new Cauchy tensor should be returned.

**Comment by epsi1on** [comment]
I think that formula is only for top/button faces. like formula `σ(max) = M.C/I = M/S`. 
More general formula should be `σ(z) = M . z / I` = `12 * M11 * z / t^3`
Also are you sure about this part?
```
cauchyStressTensor.S12 = this.M12 * 6 / Math.Pow(shellThickness, 2);
cauchyStressTensor.S21 = this.M21 * 6 / Math.Pow(shellThickness, 2);
```

**Comment by rubsy92** [comment]
You're right, it would give incorrect result between the mid-plane and the face of the shell. See the pull request for an updated version. 

What  do you mean with "i think naming is a little bit different"?

**Comment by epsi1on** [comment]
> 
> 
> You're right, it would give incorrect result between the mid-plane and the face of the shell. See the pull request for an updated version.
> 
> What do you mean with "i think naming is a little bit different"?

I mean in the tensor image above, `u13` will make `s11` variable through thickness,  but in calculation you set the 
` cauchyStressTensor.S11 = tensor.M11 * z / I;`. these naming are different.

Also i did some validation on triangle element with abaqus, buth i get `0.74%` error on nodal displacements, also abou 20% error in cauchy tensors for top face, how much error you got from last validations?

**Comment by rubsy92** [comment]
Which elements did you use in Abaqus? The implemented shell formulation should be identical to the STRI3 elements of Abaqus. A simple plate, clamped on one side and loaded on the other side in all directions gives my almost perfect nodal displacements (error of 0.003% at the end of the plate). I did not check complex 3D structures...

**Comment by epsi1on** [comment]
I validated with this example
https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/tree/master/BriefFiniteElementNet.Validation/Data/FlatShell%20-%20triangle/IBeamTorsion

Pls. look at images and[ intro.md file](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/blob/master/BriefFiniteElementNet.Validation/Data/FlatShell%20-%20triangle/IBeamTorsion/Intro.md)

**Comment by epsi1on** [comment]
> 
> 
> Which elements did you use in Abaqus? The implemented shell formulation should be identical to the STRI3 elements of Abaqus. A simple plate, clamped on one side and loaded on the other side in all directions gives my almost perfect nodal displacements (error of 0.003% at the end of the plate). I did not check complex 3D structures...

In this directory there are validation cases:

https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/tree/master/BriefFiniteElementNet.Validation/Data/FlatShell%20-%20triangle

Can you please create another folder for your simple clamped plate and its files just like above folder? I have not Abaqus on my PC.

Thanks

**Comment by rubsy92** [comment]
> 
> 
> I validated with this example
> https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/tree/master/BriefFiniteElementNet.Validation/Data/FlatShell%20-%20triangle/IBeamTorsion
> 
> Pls. look at images and[ intro.md file](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/blob/master/BriefFiniteElementNet.Validation/Data/FlatShell%20-%20triangle/IBeamTorsion/Intro.md)
> 
> this is implementation of example 13 in this PDF file (page 136 of pdf or 145/175), same formulations as this file is used `DktHelper` and `CstHelper` class.
> https://pdfs.semanticscholar.org/581b/ea64790f0162cee58977edc747f489592a90.pdf
> 
> Thanks

Do you have the abaqus CAE file? This would be helpful so I wouldn't need to model it myself.

**Comment by epsi1on** [comment]
unfortunately i do not have the abaqus .cae file

**Comment by rubsy92** [comment]
> 
> 
> > You're right, it would give incorrect result between the mid-plane and the face of the shell. See the pull request for an updated version.
> > What do you mean with "i think naming is a little bit different"?
> 
> I mean in the tensor image above, `u13` will make `s11` variable through thickness, but in calculation you set the
> ` cauchyStressTensor.S11 = tensor.M11 * z / I;`. these naming are different.
> 
> Also I did some validation on triangle element with abaqus, buth i get `0.74%` error on nodal displacements, also about 20% error in Cauchy tensors for top face (pls. look at [here](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/tree/master/BriefFiniteElementNet.Validation/Data/FlatShell%20-%20triangle/IBeamTorsion)) , how much error you got from last validations? i'm not sure if problem with my calculations.
> 
> ![image](https://user-images.githubusercontent.com/7839141/89996304-df26e380-dc9f-11ea-8bd0-e1d35a082a2c.png)

I've done a quick and dirty test on the I beam and I get von Mises stresses which are roughly between ±1.5% with Abaqus (STRI3 element). Note that I only validated a small amount of points so the error can be higher, however it's a good ballpark estimate. I'm having some issues with the new current implementation of the matrix operations - see #78
