### ISSUE TITLE
Applying curvature to elements

### ISSUE THREAD

**Issue by darrenmjones** [BriefFiniteElementNet/BriefFiniteElement.Net#46]
Hi, is it possible to apply a moment as a uniform load along an element ?  I want to analyse the effects of differential temperature through the depth of a beam.  The `BriefFiniteElementNet.Loads.UniformLoad` only allows a XYZ vector, no moments.

**Comment by epsi1on** [comment]
Hi,
There is not yet implementation of distributed moments, but there are some for concentrated moments. Maybe you can use multiple concentrated loads to get something near the distributed moment.

**Comment by darrenmjones** [comment]
Thank you.  I think I could apply node moments at each end of the beam and then subtract those moments from the analysis ones to give the secondary moments.
