### ISSUE TITLE
Rotational spring element

### ISSUE THREAD

**Issue by NickN-Eng** [BriefFiniteElementNet/BriefFiniteElement.Net#49]
Hi epsi1on,

Is there a way of achieving a spring in rotation only? I.e. between 2 nodes:
Dx, Dy, Dz - fixed
Rx - kNm/rad
Ry - kNm/rad
Rz - kNm/rad

I see that there is already the spring1d element, but it seems like that is for translations, not rotations? Apologies, I am not familiar enough with FEM theory to know.

**Comment by epsi1on** [comment]
Yes you are right,
I think i should add such spring to `BriefFiniteElementNet.CustomElements`

**Comment by epsi1on** [comment]
I think this is good starting point
https://opensees.berkeley.edu/wiki/index.php/Two_Node_Link_Element

**Comment by epsi1on** [comment]
Al element named `BriefFiniteElementNet.CustomElements.ParametricSpring` added  (f29cdf8)
