### ISSUE TITLE
7 degree of freedom (DoF)

### ISSUE THREAD

**Issue by dawiddyrcz** [BriefFiniteElementNet/BriefFiniteElement.Net#53]
Is the BriefFiniteElement.Net library support the 7th degree of freedom (DoF)? 
If not, how do you think Is the possibility to extend functionality of this library by 7th DoF? 

https://enterfea.com/degrees-of-freedom-in-fea/

**Comment by epsi1on** [comment]
I'm not sure, can you please give an example that uses 7'th DoF?
I've not seen this yet, so have no idea about it.

Thanks

**Comment by dawiddyrcz** [comment]
7 dof is responsible for section warping which for non closed profiles causing additional stress. 
[7dofFiniteElementMethod.pdf](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/files/4815662/7dofFiniteElementMethod.pdf)

**Comment by epsi1on** [comment]
No, at least not yet. Is it related to nonlinear analysis?

**Comment by dawiddyrcz** [comment]
It is linear analysis.

**Comment by epsi1on** [comment]
OK, i think for having this feature in the library a new element should be implemented, or at least a new ElementHelper.
Added enhancement to this issue
