### ISSUE TITLE
Modelling equivalent loads - general approach using this library

### ISSUE THREAD

**Issue by raxdev** [BriefFiniteElementNet/BriefFiniteElement.Net#65]
Hi,

This is not a bug report, but rather question about how to use the library for equivalent loads and equivalent loads in general.

I would like to compute and visualize result of prestressing in a simple bar element. The prestressing comes in a form of a tendon with various profiles (linear, parabollic, V-shaped, zig-zag). 
I've learned that the best way to find the impact of prestressing is to calculate equivalent loads that cause the same effect as prestressing. 
Could you please let me know how to model it using the library ?

For example, if the tendon is parabollic, I can use the simplified method:
![image](https://user-images.githubusercontent.com/174672/87022136-57e4dc80-c1d6-11ea-97b7-be2229daa627.png)
I assume, that in this case, I in the library need to apply following loads to the bar element (e0 with two nodes n0 and n1):
```
model.Nodes["n0"].Loads.Add(new NodalLoad(new Force(0,0,0,0,Ma),LoadCase.DefaultLoadCase));
model.Nodes["n1"].Loads.Add(new NodalLoad(new Force(0, 0, 0, 0, Mb), LoadCase.DefaultLoadCase));
model.Elements["e0"].Loads.Add(new UniformLoad(wp));

```
When the tendon has more irregular shape, I've found an algorithm that suggests dividing it into small segments in which we can assume it's linear, and then to compute:
- loads in x & z directions (=0 if there is no loss in stressing force) and moment about y axis at the start / end of the segment
- distributed loads in x & z direction (=0 if no loss) and moment about y axis at the segment

I assume in this complex case I need to replace a single bar element with smaller bar elements linked together - one small bar for one small segment where I tendon is linear? If so, how I can apply the computed values to such linked model?

**Comment by epsi1on** [comment]
> I would like to compute and visualize result of prestressing in a simple bar element. The prestressing comes in a form of a tendon with various profiles (linear, parabollic, V-shaped, zig-zag).

Could you please give an illustration?
> I've learned that the best way to find the impact of prestressing is to calculate equivalent loads that cause the same effect as prestressing.

Yes, and i think this is only way in this library to consider pre-stressed elements,

> For example, if the tendon is parabollic, I can use the simplified method:
> ![image](https://user-images.githubusercontent.com/174672/87022136-57e4dc80-c1d6-11ea-97b7-be2229daa627.png)
> I assume, that in this case, I in the library need to apply following loads to the bar element (e0 with two nodes n0 and n1):

I've found this image from wikipedia:
Is it what you do mean?

![image](https://user-images.githubusercontent.com/7839141/87028535-f9c6f200-c1f3-11ea-9030-741379b26bd1.png)

or this one

![image](https://user-images.githubusercontent.com/7839141/87028917-95586280-c1f4-11ea-9622-6466e354c3b2.png)

**Comment by raxdev** [comment]
The pictures you kindly included are illustrating exactly my problem.
I would like to understand how to solve such problem in simplest case (parabolic) with the library and  then, how to generalize the approach to solve more complex constructs, like on the illustration below (I draw that myself - the vertical bars are the sections I would like to compute separately to get more accurate result)

![image](https://user-images.githubusercontent.com/174672/87032161-7520a780-c1e4-11ea-8833-baa9686976ed.png)

**Comment by raxdev** [comment]
Also, my previous picture illustrating the problem comes from[ this publication](https://www.pci.org/PCI_Docs/Publications/PCI%20Journal/1977/March-1977/Shear%20Component%20of%20Prestress%20by%20Equivalent%20Loads.pdf).

**Comment by epsi1on** [comment]
i think first step is to idealize the model. As you said, splitting the beam into smaller elements is a good idea, but you also should consider each element with constant properties, i mean the tendon in element cannot have slope, only should have horizontal tendon (red lines are tendons)

![image](https://user-images.githubusercontent.com/7839141/87048879-846a1a00-c211-11ea-95c8-f9b5afa5ae28.png)

next step is to apply nodal load to each, which is a load and a moment on each middle node. for each node one force and moment for right element, and one for left element.

But also note that your model probably falls into nonlinear criteria, but this library is only for linear analysis.

Thanks

**Comment by epsi1on** [comment]
I'm not sure about the above solution, does it work for you?

**Comment by raxdev** [comment]
Hi,

I'm still trying to verify that :) Thank you!
