### ISSUE TITLE
StackOverflow-Exception

### ISSUE THREAD

**Issue by thaletob** [BriefFiniteElementNet/BriefFiniteElement.Net#76]
The Overflow-Exception happens with Quad-Elements. After debugging I found out that the error is caused by DkqHelper.cs -> `GetDMatrixAt` which refers to itself in line 309:` var diff = (tangent - GetDMatrixAt(targetElement, isoCoords)).Max(ii=>Math.Abs(ii));`
Due to this infinite loop the StackOverflowException is created somewhere in GetDMatrixAt.
My previous version (06/2020) is working.

**Comment by epsi1on** [comment]
Hi,
I think you and @rubsy92 was working on the quadrilateral element. Maybe he knows the solution

Thanks

**Comment by epsi1on** [comment]
temporary fixed by commenting out the line 309 of `DkqHelper.cs`, can you please check and see if problem still exists?

**Comment by rubsy92** [comment]
Commenting out that line fixes the issue indeed. What is the function of that diff term? It is not used anywhere...

**Comment by epsi1on** [comment]
I think last time it is used by breakpoint to manually check with known value :)

**Comment by rubsy92** [comment]
@epsi1on You have a pull request which fixes this. It also gives some benchmark data of triangular shell elements (incl. Abaqus data)

**Comment by epsi1on** [comment]
> 
> 
> @epsi1on You have a pull request which fixes this. It also gives some benchmark data of triangular shell elements (incl. Abaqus data)

Thanks,
Can you please recheck your pull request, there is two issues with this:
- It had some conflicts with current code (i've fixed it but see next item)
- It cannot compile because reference to visual studio debugger visualizers is missing,

Thanks

**Comment by epsi1on** [comment]
I think this issue is fixed,
Please feel free to reopen if still exists
Thanks
