### ISSUE TITLE
Result don't match hand calculations and SAP2000 results

### ISSUE THREAD

**Issue by cmoha** [BriefFiniteElementNet/BriefFiniteElement.Net#79]
**Describe the bug**

Hello Dear,
I have done some hand calculations and SAP2000 of examples given [here ](https://bfenet.readthedocs.io/en/latest/example/inclinedframe/index.html) and [here](https://bfenet.readthedocs.io/en/latest/example/loadcasecomb/index.htm) and i don't get same results.

**To Reproduce**
This is the code We've used and caused wrong result/ runtime error

```
        [Test]
        public void TestMethod3()
        {
            var model = new Model();

            var n0 = new Node(-10, 0, 0);
            var n1 = new Node(-10, 0, 6);
            var n2 = new Node(0, 0, 8);
            var n3 = new Node(10, 0, 6);
            var n4 = new Node(10, 0, 0);
                 
            model.Nodes.Add(n0, n1, n2, n3, n4);
            n0.Constraints =n4.Constraints = Constraints.Fixed;


            var secAA = new Sections.UniformGeometric1DSection(SectionGenerator.GetISetion(0.24, 0.67, 0.01, 0.006));
            var secBB = new Sections.UniformGeometric1DSection(SectionGenerator.GetISetion(0.24, 0.52, 0.01, 0.006));
            var mat = Materials.UniformIsotropicMaterial.CreateFromYoungPoisson(210e9, 0.3);

            var e1 = new BarElement(n0, n1) { Material = mat, Section = secAA };
            var e2 = new BarElement(n1, n2) { Material = mat, Section = secBB };
            var e3 = new BarElement(n2, n3) { Material = mat, Section = secBB };
            var e4 = new BarElement(n3, n4) { Material = mat, Section = secAA };

            model.Elements.Add(e1, e2, e3, e4);

            var u1 = new Loads.UniformLoad(LoadCase.DefaultLoadCase, new Vector(0, 0, 1), -6000, CoordinationSystem.Global);
            var u2 = new Loads.UniformLoad(LoadCase.DefaultLoadCase, new Vector(0, 0, 1), -5000, CoordinationSystem.Local);

            e2.Loads.Add(u1);
            e3.Loads.Add(u2);

            model.Solve_MPC();

            var n4Force = n4.GetSupportReaction();
            Console.WriteLine("Support reaction of n4: {0}", n4Force);

        }
```

**Expected behavior**
Results of [this example](https://bfenet.readthedocs.io/en/latest/example/inclinedframe/index.html) are writen 
_Support reaction of n4: F: -37514.9891729259, 0, 51261.532772234, M: 0, -97714.6039503916, 0_
but SAP2000 gives me this result  
![Capture](https://user-images.githubusercontent.com/10573467/92281105-3749b200-eefb-11ea-9f4b-f746953ad2d0.PNG)

**Comment by epsi1on** [comment]
Hi
Thanks for details.
We can fix it easily. First need to make sure we are using same model. This is same model as BFE example you mentioned, but uniform loads are removed, also a new load is applied on the `n1` node:

![image](https://user-images.githubusercontent.com/7839141/92312170-97138c00-efd3-11ea-8141-b8a5fdeb113c.png)

output for such model in bfe is:
- Support reaction on `N0`: F:{-3140,0,-375} and M:{0,-13218,0}
- Support reaction on `N4`: F:{-1859,0,375} and M:{0,-9278,0}

Can you please analyze this frame in SAP2000 and give me the support reactions output of model?

Thanks

**Comment by cmoha** [comment]
Good day dear,

Code used for generating your model is 
```
 [Test]
        public void TestMethod4()
        {
            var model = new Model();

            var n0 = new Node(-10, 0, 0);
            var n1 = new Node(-10, 0, 6);
            var n2 = new Node(0, 0, 8);
            var n3 = new Node(10, 0, 6);
            var n4 = new Node(10, 0, 0);

            model.Nodes.Add(n0, n1, n2, n3, n4);
            n0.Constraints = n4.Constraints = Constraints.Fixed;


            var secAA = new Sections.UniformGeometric1DSection(SectionGenerator.GetISetion(0.24, 0.67, 0.01, 0.006));
            var secBB = new Sections.UniformGeometric1DSection(SectionGenerator.GetISetion(0.24, 0.52, 0.01, 0.006));
            var mat = Materials.UniformIsotropicMaterial.CreateFromYoungPoisson(210e9, 0.3);

            var e1 = new BarElement(n0, n1) { Material = mat, Section = secAA };
            var e2 = new BarElement(n1, n2) { Material = mat, Section = secBB };
            var e3 = new BarElement(n2, n3) { Material = mat, Section = secBB };
            var e4 = new BarElement(n3, n4) { Material = mat, Section = secAA };

            model.Elements.Add(e1, e2, e3, e4);

            n1.Loads.Add(new NodalLoad(new Force(5000, 0, 0, 0, 0, 0)));

            model.Solve_MPC();

            var n0Force = n0.GetSupportReaction();
            var n4Force = n4.GetSupportReaction();
            Console.WriteLine("Support reaction of n0: {0}", n0Force);
            Console.WriteLine("Support reaction of n4: {0}", n4Force);

```
results from unit test gave 
![image](https://user-images.githubusercontent.com/10573467/92333651-83c1f880-f087-11ea-8686-625cf8980e71.png)

and my output is matching with your output 

SAP2000 output gave me 
![image](https://user-images.githubusercontent.com/10573467/92333673-b2d86a00-f087-11ea-8782-364b1823e1c0.png)

results are varying between 100.67% to 99.03%

**Comment by epsi1on** [comment]
I think for such simple model, there should be no error. So i think there is a difference in BFE model and SAP2000 model. Lets check the calculated value of sections. 
- SecAA (two columns): Area: `0.0087`, Iy:`0.000660`, Iz:`2.30517-05`
- SecBB (two sloped beams): Area: `0.0078`, Iy:`0.00037466`, Iz:`2.3049E-05`
- Material: (all members): Young mudule: `210e9`, Poisson's ratio :`0.3`
Can you please check these values with your model in SAP2000?

Thanks

**Comment by cmoha** [comment]
Sorry for late reply,
these are section properties and material data calculated from sap2000 


![image](https://user-images.githubusercontent.com/10573467/92992920-96f12000-f4ee-11ea-9df3-eac15f9fb175.png)

![image](https://user-images.githubusercontent.com/10573467/92992933-aa03f000-f4ee-11ea-85e8-f42a2e80f29d.png)

![image](https://user-images.githubusercontent.com/10573467/92994268-39160580-f4f9-11ea-9ac6-2fdb1843ead2.png)

**Comment by epsi1on** [comment]
Calculated geometric and mechanical properties are identical. But seems SAP2000 do not use EulerBernoully formulation for beam by default (have a look at [here ](https://www.eng-tips.com/viewthread.cfm?qid=400940) and [here](https://www.researchgate.net/post/Calculating_beam_nodal_displacements_rotations_using_SAP2000_and_programming_system_matrices_in_MATLAB-Differences_in_responses)) but this library uses EulerBernoully beam formulation by default. SAP2000 uses a formulation like Timoshenko beam, and maybe the 1% difference is because of that.
Can you please set the shear property modifiers of section to zero and check the result again? that way results will be identical I think...
Thanks

**Comment by epsi1on** [comment]
Hi,
Did you check by setting shear property modifiers to zero? That way they should give identical result.

**Comment by cmoha** [comment]
Hi,
Yes I have rechecked these parameters and they are now the same values,
You can now close this issue.
Thank you for your time.

**Comment by epsi1on** [comment]
Does the result match for uniform load also? I mean model in first post.

Thanks
