### ISSUE TITLE
Timoshenko beam

### ISSUE THREAD

**Issue by rubsy92** [BriefFiniteElementNet/BriefFiniteElement.Net#8]
Hi,

I noticed that Timoshenko beams are not yet implemented. Do you have a timescale for when this would be available or can you give access to the used sources (more explanation) so I can implement them?

Thanks!

**Comment by epsi1on** [comment]
Hi,
Yes Timoshenko beam is not implemented yet. I also have to timescale for it as i'm working on partial end release of beams and multi node beams for now.
If you are interested to code it, you should edit [TimoshenkoBeamHelper.cs](https://github.com/epsi1on/BFE.Net/blob/master/BriefFiniteElementNet/ElementHelpers/TimoshenkoBeamHelper.cs) file. The most important section is 

``public Matrix CalcLocalKMatrix(Element targetElement)``

method. I have not reference for Timoshenko beam calculation, but i believe you can find some with search engines.
Please let me know if you have problems in integrating your code with current structure of BFE library, i will definitely try to solve problems as much as possible.

Thanks

**Comment by rubsy92** [comment]
Hi,

Thanks for the fast feedback! I'm trying some things here and now I'm stuck at the "GetBMatrixAt" method. Here I clearly need to fill in the modified functions to take shear into account. However I can't immediately find the correct functions. Do you know where I should get those? 

Thanks!

PS Interesting that you're working on multi-node beams. How far are you in that stage?

**Comment by epsi1on** [comment]
Actually i'm not familiar with Timoshenko beam calculations. But there is a unified way to calculate the stiffness matrix of a finite element and that is 

[click to see formula](http://rogercortesi.com/eqn/tempimagedir/eqn5191.png)

the GetBMatrix and GetDMatrix are no where used outside the class yet! so it means for start it is better to simply implement Timoshenko beam in a way that it just works (i.e. the get stiffness matrix work correctly). In next step after that we can decompose calculations into standard formula i just said and will implement B and D matrix.

> PS Interesting that you're working on multi-node beams. How far are you in that stage?

that is almost done, only stuck at partial end release condition in multi-node beams. 

Thanks

**Comment by epsi1on** [comment]
Please let me know if there is issue for implementing timoshenko beam into the library.
What formulation you want to use? can you please share the documents if possible?

Thanks

**Comment by rubsy92** [comment]
Hi I'm currently reading in "concepts and applications of finite element analysis" and there the Timoshenko beam element stiffness matrix is fully written down there. It's actually the same as in your frameElement2D calass, GetLocalStiffnessMatrix method.

**Comment by epsi1on** [comment]
thanks, 
can you please pull your changes into source code as a pull request?

thanks

**Comment by rubsy92** [comment]
I'm having some issues implementing/validating it for now. Once i know it's correct ill push it.

**Comment by rubsy92** [comment]
Okay, I'm validating now. I'll let you know if it checks out. 

PS. Is it possibile to have a boundary condition that acts like the floor? I.e. it can be compressed, but it cannot take tension.

**Comment by epsi1on** [comment]
> Is it possibile to have a boundary condition that acts like the floor? I.e. it can be compressed, but it cannot take tension.

that is a nonlinear behavior, not yet possible to add nonlinear stuff to main branch.

**Comment by epsi1on** [comment]
> 
> 
> Okay, I'm validating now. I'll let you know if it checks out.
> 
> PS. Is it possibile to have a boundary condition that acts like the floor? I.e. it can be compressed, but it cannot take tension.

Hello,
Any news?
