### ISSUE TITLE
Project cleanup: usage of params keyword.

### ISSUE THREAD

**Issue by wo80** [BriefFiniteElementNet/BriefFiniteElement.Net#80]
There are a lot of methods that use `params double[] args` as function parameter. Since this hides the array allocation, I suggest to remove the `params` keyword.

**Comment by epsi1on** [comment]
The param keyworks are at most size of 3, mostly for getting iso-parametric coordinates. Not sure but maybe array with three members (24 byte or less) do not cause serious problem

**Comment by wo80** [comment]
There are a couple of methods in the `Matrix` class that use `params`, those will be removed with #72 . Doing a quick `grep` I found 227 occurances, but most of them seem to be related to iso coords, as you said, and I think that's a valid use case. Memory profiling will show if it's a problem.
