### ISSUE TITLE
Defining the hinge joint constraint.

### ISSUE THREAD

**Issue by samuto** [BriefFiniteElementNet/BriefFiniteElement.Net#82]
**Description**

First thanks for sharing such an amazing FEA project on GitHub. 

I went through the latest document and the examples, but can't find any instruction on how to set up the hinge constraint between structural elements.  It would be much appreciated if you can share one simple example code on how to define the hinge joint.

Many thanks.

**To Reproduce**
none

**Comment by samuto** [comment]
I Apology, can't change the label to other categories rather than "bug".

**Comment by epsi1on** [comment]
I'll add the example to examples section also the code for HingLink is not tested yet.
Usage is simple, simply create a `HingLink`, then add two nodes that you want connect them and finally add the element into the Model, `VirtualConstraint` is also a MpcElement, take a look at documentation here: https://bfenet.readthedocs.io/en/latest/elements/mpcelements/vconstraint/index.html

Can you please validate the `HingLink` result and see if it have any bug etc.?
Thanks

**Comment by samuto** [comment]
Thanks for the instant reply, I will make a try and let you know soon, hopefully by this week.

**Comment by epsi1on** [comment]
please reopen if needed
