### ISSUE TITLE
FrameElement2Node still in use?

### ISSUE THREAD

**Issue by rubsy92** [BriefFiniteElementNet/BriefFiniteElement.Net#87]
Hi @epsi1on,

I'm working on the obsolete code project (See https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/projects/4#card-45815267) and I came across the FrameElement2Node element. This class became obsolete, no? Everything refers to barElement now, right?

**Comment by epsi1on** [comment]
Hi,
yes you are right. `FrameElement2Node` is deprecated and `BarElemenet` should be used instead.

**Comment by rubsy92** [comment]
Hi @epsi1on 

See the pull request for the moving of obsolete code to the legacy project.

**Comment by epsi1on** [comment]
Hi,
Thanks. Seems there is error in code which cannot be built. Could you please do a check?

**Comment by epsi1on** [comment]
`FrameElement2Node` and other obsolete elements are moved to `Legacy` project.
