### ISSUE TITLE
Add validation for MpcElements

### ISSUE THREAD

**Issue by epsi1on** [BriefFiniteElementNet/BriefFiniteElement.Net#90]
Adding a validation that :

- Uses `MpcElements.RigidElement` as rigid element, 
- all nodes are free of constraint and uses `MpcElements.VirtualSupport` for constraining nodal DoFs.
- Validate for `MpcElements.HingLink`

**Comment by epsi1on** [comment]
Hi @rubsy92 ,
Would you like to please handle this issue?

Thanks

**Comment by rubsy92** [comment]
Hi @epsi1on ,

Okay, I'll check it out. Do you have a certain type of elements in mind (e.g. bar-element/shell/...)? Or do you prefer to have these tests for all types of elements?

**Comment by epsi1on** [comment]
No this is for MPC (Multy Point Constraint) Elements. For erxample `BriefFiniteElementNet.MpcElements.RigidElement_Mpc` is MpcElement, which is an un-deformable element. There is difference between this type of element with other elements like BarElement or triangle element. These MPC elements (which are inherited from `MpcElement`) do add extra equations to the system instead of affecting stiffness matrix.

**Comment by epsi1on** [comment]
this is example for deprecated `RigidElement`:

https://www.codeproject.com/Articles/850733/RigidElements-in-BriefFiniteElement-NET

New version of `RigidElement` is `RigidElement_MPC` which needs to be validated

**Comment by rubsy92** [comment]
Yes, I know. But I was referring to the other elements on which you connect the MPC element. E.g. Beams + rigid or shells + rigid?
I implemented a class for the rigid-element in combination with some beam elements. Can you check if this is the thing you have in mind? If so I'll do the others too.

**Comment by epsi1on** [comment]
I think the simple validation of Beam>RigidElement>Beam would do good job.
If we want to improve the validation at any time, then can use a more complex model. I think the type of other element do not matters so much, but having multiple rigid element in combination with other elements, or even connect two rigid elements with a `HingLink` would be a good validation and can show us possible errors.

**Comment by rubsy92** [comment]
Hi @epsi1on,

What is the difference between a VirtualSupport and a boundary condition? If it is the same I can make a test example with 2 times the same structure, but once refraining it from moving with a boundary condition and once with a VirtualSupport.

**Comment by epsi1on** [comment]
Hi,
`VirtualSupport` and nodal boundary conditions are same, only difference is that `VirtualSupport` can ba activated based on `LoadCase` and `LoadNature` (for more info pls. see [here](https://bfenet.readthedocs.io/en/latest/elements/mpcelements/index.html), `MpcElement.UseForAllLoads`, `MpcElement.AppliedLoadCases` and `MpcElement.AppliedLoadTypes`), but nodal boundary conditions are applied for all `LoadCase`s and `LoadNature`s.

Thanks

**Comment by epsi1on** [comment]
Validation.Case_04 is about rigid element
