### ISSUE TITLE
Question about available Solvers

### ISSUE THREAD

**Issue by thaletob** [BriefFiniteElementNet/BriefFiniteElement.Net#99]
Hello again,
I am actually trying out the two different solvers available. In my case I've got structures with about 11000 Quad-Shell-Elements. In contrast to your documentation the Cholesky-Solver is much faster (about 2x faster) than the Gradient Solver.
(Cholesky takes about 16.5 to 17.5 s to solve, the gradient-solver needs about 28 to 41 s)

Do you have any ideas why? I am just wondering because I never got a problem where the direct solver is faster than the iterative one.

Greetings and thanks for the great work!

**Comment by epsi1on** [comment]
Can you please send the code snippet to reproduce the issue?
Not sure what is the reason...

**Comment by thaletob** [comment]
When I'm testing it for smaller models, then the gradient solver is much faster. But in this case I am using it in an optimization-procedure with many solver-calls. The model-properties do not change. I just changed the solver type by adding `BuiltInSolverType.ConjugateGradient` to the `model.Solve()` call. 
As I mentioned... this leads to a smaller calculation time for small structures but a larger calculation time for big models. So it's more like a question than an issue...

**Comment by epsi1on** [comment]
It could be a bug, but cannot exactly tell you what is the reason unless trace the code...
